version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_library.yaml
    flatten: true
    excludes: # put task names in here which are overwritten in this file
      - generate:generate
      - generate:code
    vars:
      CODE_DIRS: '{{.ROOT_DIR}}/proto/...'
      GENERATE_DOCS_INDEX: "false"
