// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kms/api/cmk/trust/oidc/flow/v1/flow.proto

package flowv1

import (
	v1 "github.com/openkcm/api-sdk/proto/kms/api/cmk/trust/oidc/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_kms_api_cmk_trust_oidc_flow_v1_flow_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*v1.OIDC)(nil),
		ExtensionType: ([]*Attribute)(nil),
		Field:         50,
		Name:          "kms.api.cmk.trust.oidc.flow.v1.auth_attributes",
		Tag:           "bytes,50,rep,name=auth_attributes",
		Filename:      "kms/api/cmk/trust/oidc/flow/v1/flow.proto",
	},
	{
		ExtendedType:  (*v1.OIDC)(nil),
		ExtensionType: ([]*Attribute)(nil),
		Field:         51,
		Name:          "kms.api.cmk.trust.oidc.flow.v1.token_attributes",
		Tag:           "bytes,51,rep,name=token_attributes",
		Filename:      "kms/api/cmk/trust/oidc/flow/v1/flow.proto",
	},
	{
		ExtendedType:  (*v1.OIDC)(nil),
		ExtensionType: ([]*Attribute)(nil),
		Field:         52,
		Name:          "kms.api.cmk.trust.oidc.flow.v1.logout_attributes",
		Tag:           "bytes,52,rep,name=logout_attributes",
		Filename:      "kms/api/cmk/trust/oidc/flow/v1/flow.proto",
	},
	{
		ExtendedType:  (*v1.OIDC)(nil),
		ExtensionType: ([]*Attribute)(nil),
		Field:         53,
		Name:          "kms.api.cmk.trust.oidc.flow.v1.auth_context",
		Tag:           "bytes,53,rep,name=auth_context",
		Filename:      "kms/api/cmk/trust/oidc/flow/v1/flow.proto",
	},
}

// Extension fields to v1.OIDC.
var (
	// repeated kms.api.cmk.trust.oidc.flow.v1.Attribute auth_attributes = 50;
	E_AuthAttributes = &file_kms_api_cmk_trust_oidc_flow_v1_flow_proto_extTypes[0]
	// repeated kms.api.cmk.trust.oidc.flow.v1.Attribute token_attributes = 51;
	E_TokenAttributes = &file_kms_api_cmk_trust_oidc_flow_v1_flow_proto_extTypes[1]
	// repeated kms.api.cmk.trust.oidc.flow.v1.Attribute logout_attributes = 52;
	E_LogoutAttributes = &file_kms_api_cmk_trust_oidc_flow_v1_flow_proto_extTypes[2]
	// repeated kms.api.cmk.trust.oidc.flow.v1.Attribute auth_context = 53;
	E_AuthContext = &file_kms_api_cmk_trust_oidc_flow_v1_flow_proto_extTypes[3]
)

var File_kms_api_cmk_trust_oidc_flow_v1_flow_proto protoreflect.FileDescriptor

const file_kms_api_cmk_trust_oidc_flow_v1_flow_proto_rawDesc = "" +
	"\n" +
	")kms/api/cmk/trust/oidc/flow/v1/flow.proto\x12\x1ekms.api.cmk.trust.oidc.flow.v1\x1a.kms/api/cmk/trust/oidc/flow/v1/attribute.proto\x1a$kms/api/cmk/trust/oidc/v1/oidc.proto:s\n" +
	"\x0fauth_attributes\x12\x1f.kms.api.cmk.trust.oidc.v1.OIDC\x182 \x03(\v2).kms.api.cmk.trust.oidc.flow.v1.AttributeR\x0eauthAttributes:u\n" +
	"\x10token_attributes\x12\x1f.kms.api.cmk.trust.oidc.v1.OIDC\x183 \x03(\v2).kms.api.cmk.trust.oidc.flow.v1.AttributeR\x0ftokenAttributes:w\n" +
	"\x11logout_attributes\x12\x1f.kms.api.cmk.trust.oidc.v1.OIDC\x184 \x03(\v2).kms.api.cmk.trust.oidc.flow.v1.AttributeR\x10logoutAttributes:m\n" +
	"\fauth_context\x12\x1f.kms.api.cmk.trust.oidc.v1.OIDC\x185 \x03(\v2).kms.api.cmk.trust.oidc.flow.v1.AttributeR\vauthContextBHZFgithub.com/openkcm/api-sdk/proto/kms/api/cmk/trust/oidc/flow/v1;flowv1b\beditionsp\xe9\a"

var file_kms_api_cmk_trust_oidc_flow_v1_flow_proto_goTypes = []any{
	(*v1.OIDC)(nil),   // 0: kms.api.cmk.trust.oidc.v1.OIDC
	(*Attribute)(nil), // 1: kms.api.cmk.trust.oidc.flow.v1.Attribute
}
var file_kms_api_cmk_trust_oidc_flow_v1_flow_proto_depIdxs = []int32{
	0, // 0: kms.api.cmk.trust.oidc.flow.v1.auth_attributes:extendee -> kms.api.cmk.trust.oidc.v1.OIDC
	0, // 1: kms.api.cmk.trust.oidc.flow.v1.token_attributes:extendee -> kms.api.cmk.trust.oidc.v1.OIDC
	0, // 2: kms.api.cmk.trust.oidc.flow.v1.logout_attributes:extendee -> kms.api.cmk.trust.oidc.v1.OIDC
	0, // 3: kms.api.cmk.trust.oidc.flow.v1.auth_context:extendee -> kms.api.cmk.trust.oidc.v1.OIDC
	1, // 4: kms.api.cmk.trust.oidc.flow.v1.auth_attributes:type_name -> kms.api.cmk.trust.oidc.flow.v1.Attribute
	1, // 5: kms.api.cmk.trust.oidc.flow.v1.token_attributes:type_name -> kms.api.cmk.trust.oidc.flow.v1.Attribute
	1, // 6: kms.api.cmk.trust.oidc.flow.v1.logout_attributes:type_name -> kms.api.cmk.trust.oidc.flow.v1.Attribute
	1, // 7: kms.api.cmk.trust.oidc.flow.v1.auth_context:type_name -> kms.api.cmk.trust.oidc.flow.v1.Attribute
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	4, // [4:8] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kms_api_cmk_trust_oidc_flow_v1_flow_proto_init() }
func file_kms_api_cmk_trust_oidc_flow_v1_flow_proto_init() {
	if File_kms_api_cmk_trust_oidc_flow_v1_flow_proto != nil {
		return
	}
	file_kms_api_cmk_trust_oidc_flow_v1_attribute_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kms_api_cmk_trust_oidc_flow_v1_flow_proto_rawDesc), len(file_kms_api_cmk_trust_oidc_flow_v1_flow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_kms_api_cmk_trust_oidc_flow_v1_flow_proto_goTypes,
		DependencyIndexes: file_kms_api_cmk_trust_oidc_flow_v1_flow_proto_depIdxs,
		ExtensionInfos:    file_kms_api_cmk_trust_oidc_flow_v1_flow_proto_extTypes,
	}.Build()
	File_kms_api_cmk_trust_oidc_flow_v1_flow_proto = out.File
	file_kms_api_cmk_trust_oidc_flow_v1_flow_proto_goTypes = nil
	file_kms_api_cmk_trust_oidc_flow_v1_flow_proto_depIdxs = nil
}
