// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: kms/api/cmk/types/v1/status.proto

package typesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED         Status = 0
	Status_STATUS_AVAILABLE           Status = 1
	Status_STATUS_PROCESSING          Status = 2
	Status_STATUS_TERMINATION_PENDING Status = 3
	Status_STATUS_TERMINATED          Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_AVAILABLE",
		2: "STATUS_PROCESSING",
		3: "STATUS_TERMINATION_PENDING",
		4: "STATUS_TERMINATED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":         0,
		"STATUS_AVAILABLE":           1,
		"STATUS_PROCESSING":          2,
		"STATUS_TERMINATION_PENDING": 3,
		"STATUS_TERMINATED":          4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_kms_api_cmk_types_v1_status_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_kms_api_cmk_types_v1_status_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_kms_api_cmk_types_v1_status_proto_rawDescGZIP(), []int{0}
}

var File_kms_api_cmk_types_v1_status_proto protoreflect.FileDescriptor

const file_kms_api_cmk_types_v1_status_proto_rawDesc = "" +
	"\n" +
	"!kms/api/cmk/types/v1/status.proto\x12\x14kms.api.cmk.types.v1*\x84\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10STATUS_AVAILABLE\x10\x01\x12\x15\n" +
	"\x11STATUS_PROCESSING\x10\x02\x12\x1e\n" +
	"\x1aSTATUS_TERMINATION_PENDING\x10\x03\x12\x15\n" +
	"\x11STATUS_TERMINATED\x10\x04B\xdb\x01\n" +
	"\x18com.kms.api.cmk.types.v1B\vStatusProtoP\x01Z=github.com/openkcm/api-sdk/proto/kms/api/cmk/types/v1;typesv1\xa2\x02\x04KACT\xaa\x02\x14Kms.Api.Cmk.Types.V1\xca\x02\x14Kms\\Api\\Cmk\\Types\\V1\xe2\x02 Kms\\Api\\Cmk\\Types\\V1\\GPBMetadata\xea\x02\x18Kms::Api::Cmk::Types::V1b\x06proto3"

var (
	file_kms_api_cmk_types_v1_status_proto_rawDescOnce sync.Once
	file_kms_api_cmk_types_v1_status_proto_rawDescData []byte
)

func file_kms_api_cmk_types_v1_status_proto_rawDescGZIP() []byte {
	file_kms_api_cmk_types_v1_status_proto_rawDescOnce.Do(func() {
		file_kms_api_cmk_types_v1_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kms_api_cmk_types_v1_status_proto_rawDesc), len(file_kms_api_cmk_types_v1_status_proto_rawDesc)))
	})
	return file_kms_api_cmk_types_v1_status_proto_rawDescData
}

var file_kms_api_cmk_types_v1_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kms_api_cmk_types_v1_status_proto_goTypes = []any{
	(Status)(0), // 0: kms.api.cmk.types.v1.Status
}
var file_kms_api_cmk_types_v1_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kms_api_cmk_types_v1_status_proto_init() }
func file_kms_api_cmk_types_v1_status_proto_init() {
	if File_kms_api_cmk_types_v1_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kms_api_cmk_types_v1_status_proto_rawDesc), len(file_kms_api_cmk_types_v1_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kms_api_cmk_types_v1_status_proto_goTypes,
		DependencyIndexes: file_kms_api_cmk_types_v1_status_proto_depIdxs,
		EnumInfos:         file_kms_api_cmk_types_v1_status_proto_enumTypes,
	}.Build()
	File_kms_api_cmk_types_v1_status_proto = out.File
	file_kms_api_cmk_types_v1_status_proto_goTypes = nil
	file_kms_api_cmk_types_v1_status_proto_depIdxs = nil
}
