// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: kms/api/cmk/types/v1/system_type.proto

package typesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemType int32

const (
	SystemType_SYSTEM_TYPE_UNSPECIFIED SystemType = 0
	SystemType_SYSTEM_TYPE_SYSTEM      SystemType = 1
	SystemType_SYSTEM_TYPE_SUBACCOUNT  SystemType = 2
)

// Enum value maps for SystemType.
var (
	SystemType_name = map[int32]string{
		0: "SYSTEM_TYPE_UNSPECIFIED",
		1: "SYSTEM_TYPE_SYSTEM",
		2: "SYSTEM_TYPE_SUBACCOUNT",
	}
	SystemType_value = map[string]int32{
		"SYSTEM_TYPE_UNSPECIFIED": 0,
		"SYSTEM_TYPE_SYSTEM":      1,
		"SYSTEM_TYPE_SUBACCOUNT":  2,
	}
)

func (x SystemType) Enum() *SystemType {
	p := new(SystemType)
	*p = x
	return p
}

func (x SystemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemType) Descriptor() protoreflect.EnumDescriptor {
	return file_kms_api_cmk_types_v1_system_type_proto_enumTypes[0].Descriptor()
}

func (SystemType) Type() protoreflect.EnumType {
	return &file_kms_api_cmk_types_v1_system_type_proto_enumTypes[0]
}

func (x SystemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemType.Descriptor instead.
func (SystemType) EnumDescriptor() ([]byte, []int) {
	return file_kms_api_cmk_types_v1_system_type_proto_rawDescGZIP(), []int{0}
}

var File_kms_api_cmk_types_v1_system_type_proto protoreflect.FileDescriptor

const file_kms_api_cmk_types_v1_system_type_proto_rawDesc = "" +
	"\n" +
	"&kms/api/cmk/types/v1/system_type.proto\x12\x14kms.api.cmk.types.v1*]\n" +
	"\n" +
	"SystemType\x12\x1b\n" +
	"\x17SYSTEM_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SYSTEM_TYPE_SYSTEM\x10\x01\x12\x1a\n" +
	"\x16SYSTEM_TYPE_SUBACCOUNT\x10\x02B\xe1\x01\n" +
	"\x18com.kms.api.cmk.types.v1B\x0fSystemTypeProtoP\x01Z?github.com/openkcm/api-sdk/proto/kms/api/cmk/types/v1;typesv1\xa2\x02\x04KACT\xaa\x02\x14Kms.Api.Cmk.Types.V1\xca\x02\x14Kms\\Api\\Cmk\\Types\\V1\xe2\x02 Kms\\Api\\Cmk\\Types\\V1\\GPBMetadata\xea\x02\x18Kms::Api::Cmk::Types::V1b\x06proto3"

var (
	file_kms_api_cmk_types_v1_system_type_proto_rawDescOnce sync.Once
	file_kms_api_cmk_types_v1_system_type_proto_rawDescData []byte
)

func file_kms_api_cmk_types_v1_system_type_proto_rawDescGZIP() []byte {
	file_kms_api_cmk_types_v1_system_type_proto_rawDescOnce.Do(func() {
		file_kms_api_cmk_types_v1_system_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kms_api_cmk_types_v1_system_type_proto_rawDesc), len(file_kms_api_cmk_types_v1_system_type_proto_rawDesc)))
	})
	return file_kms_api_cmk_types_v1_system_type_proto_rawDescData
}

var file_kms_api_cmk_types_v1_system_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kms_api_cmk_types_v1_system_type_proto_goTypes = []any{
	(SystemType)(0), // 0: kms.api.cmk.types.v1.SystemType
}
var file_kms_api_cmk_types_v1_system_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kms_api_cmk_types_v1_system_type_proto_init() }
func file_kms_api_cmk_types_v1_system_type_proto_init() {
	if File_kms_api_cmk_types_v1_system_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kms_api_cmk_types_v1_system_type_proto_rawDesc), len(file_kms_api_cmk_types_v1_system_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kms_api_cmk_types_v1_system_type_proto_goTypes,
		DependencyIndexes: file_kms_api_cmk_types_v1_system_type_proto_depIdxs,
		EnumInfos:         file_kms_api_cmk_types_v1_system_type_proto_enumTypes,
	}.Build()
	File_kms_api_cmk_types_v1_system_type_proto = out.File
	file_kms_api_cmk_types_v1_system_type_proto_goTypes = nil
	file_kms_api_cmk_types_v1_system_type_proto_depIdxs = nil
}
