// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kms/api/cmk/registry/mapping/mapping.proto

package mappingv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UnmapSystemFromTenantRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UnmapSystemFromTenantRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UnmapSystemFromTenantRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UnmapSystemFromTenantRequestMultiError, or nil if none found.
func (m *UnmapSystemFromTenantRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UnmapSystemFromTenantRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ExternalId

	// no validation rules for Type

	// no validation rules for TenantId

	if len(errors) > 0 {
		return UnmapSystemFromTenantRequestMultiError(errors)
	}

	return nil
}

// UnmapSystemFromTenantRequestMultiError is an error wrapping multiple
// validation errors returned by UnmapSystemFromTenantRequest.ValidateAll() if
// the designated constraints aren't met.
type UnmapSystemFromTenantRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UnmapSystemFromTenantRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UnmapSystemFromTenantRequestMultiError) AllErrors() []error { return m }

// UnmapSystemFromTenantRequestValidationError is the validation error returned
// by UnmapSystemFromTenantRequest.Validate if the designated constraints
// aren't met.
type UnmapSystemFromTenantRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UnmapSystemFromTenantRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UnmapSystemFromTenantRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UnmapSystemFromTenantRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UnmapSystemFromTenantRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UnmapSystemFromTenantRequestValidationError) ErrorName() string {
	return "UnmapSystemFromTenantRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UnmapSystemFromTenantRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUnmapSystemFromTenantRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UnmapSystemFromTenantRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UnmapSystemFromTenantRequestValidationError{}

// Validate checks the field values on UnmapSystemFromTenantResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UnmapSystemFromTenantResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UnmapSystemFromTenantResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UnmapSystemFromTenantResponseMultiError, or nil if none found.
func (m *UnmapSystemFromTenantResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UnmapSystemFromTenantResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return UnmapSystemFromTenantResponseMultiError(errors)
	}

	return nil
}

// UnmapSystemFromTenantResponseMultiError is an error wrapping multiple
// validation errors returned by UnmapSystemFromTenantResponse.ValidateAll()
// if the designated constraints aren't met.
type UnmapSystemFromTenantResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UnmapSystemFromTenantResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UnmapSystemFromTenantResponseMultiError) AllErrors() []error { return m }

// UnmapSystemFromTenantResponseValidationError is the validation error
// returned by UnmapSystemFromTenantResponse.Validate if the designated
// constraints aren't met.
type UnmapSystemFromTenantResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UnmapSystemFromTenantResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UnmapSystemFromTenantResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UnmapSystemFromTenantResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UnmapSystemFromTenantResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UnmapSystemFromTenantResponseValidationError) ErrorName() string {
	return "UnmapSystemFromTenantResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UnmapSystemFromTenantResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUnmapSystemFromTenantResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UnmapSystemFromTenantResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UnmapSystemFromTenantResponseValidationError{}

// Validate checks the field values on MapSystemToTenantRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MapSystemToTenantRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MapSystemToTenantRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MapSystemToTenantRequestMultiError, or nil if none found.
func (m *MapSystemToTenantRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *MapSystemToTenantRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ExternalId

	// no validation rules for Type

	// no validation rules for TenantId

	if len(errors) > 0 {
		return MapSystemToTenantRequestMultiError(errors)
	}

	return nil
}

// MapSystemToTenantRequestMultiError is an error wrapping multiple validation
// errors returned by MapSystemToTenantRequest.ValidateAll() if the designated
// constraints aren't met.
type MapSystemToTenantRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MapSystemToTenantRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MapSystemToTenantRequestMultiError) AllErrors() []error { return m }

// MapSystemToTenantRequestValidationError is the validation error returned by
// MapSystemToTenantRequest.Validate if the designated constraints aren't met.
type MapSystemToTenantRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MapSystemToTenantRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MapSystemToTenantRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MapSystemToTenantRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MapSystemToTenantRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MapSystemToTenantRequestValidationError) ErrorName() string {
	return "MapSystemToTenantRequestValidationError"
}

// Error satisfies the builtin error interface
func (e MapSystemToTenantRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMapSystemToTenantRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MapSystemToTenantRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MapSystemToTenantRequestValidationError{}

// Validate checks the field values on MapSystemToTenantResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MapSystemToTenantResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MapSystemToTenantResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MapSystemToTenantResponseMultiError, or nil if none found.
func (m *MapSystemToTenantResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *MapSystemToTenantResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return MapSystemToTenantResponseMultiError(errors)
	}

	return nil
}

// MapSystemToTenantResponseMultiError is an error wrapping multiple validation
// errors returned by MapSystemToTenantResponse.ValidateAll() if the
// designated constraints aren't met.
type MapSystemToTenantResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MapSystemToTenantResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MapSystemToTenantResponseMultiError) AllErrors() []error { return m }

// MapSystemToTenantResponseValidationError is the validation error returned by
// MapSystemToTenantResponse.Validate if the designated constraints aren't met.
type MapSystemToTenantResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MapSystemToTenantResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MapSystemToTenantResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MapSystemToTenantResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MapSystemToTenantResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MapSystemToTenantResponseValidationError) ErrorName() string {
	return "MapSystemToTenantResponseValidationError"
}

// Error satisfies the builtin error interface
func (e MapSystemToTenantResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMapSystemToTenantResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MapSystemToTenantResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MapSystemToTenantResponseValidationError{}

// Validate checks the field values on GetRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetRequestMultiError, or
// nil if none found.
func (m *GetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ExternalId

	// no validation rules for Type

	if len(errors) > 0 {
		return GetRequestMultiError(errors)
	}

	return nil
}

// GetRequestMultiError is an error wrapping multiple validation errors
// returned by GetRequest.ValidateAll() if the designated constraints aren't met.
type GetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRequestMultiError) AllErrors() []error { return m }

// GetRequestValidationError is the validation error returned by
// GetRequest.Validate if the designated constraints aren't met.
type GetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRequestValidationError) ErrorName() string { return "GetRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRequestValidationError{}

// Validate checks the field values on GetResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetResponseMultiError, or
// nil if none found.
func (m *GetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	if len(errors) > 0 {
		return GetResponseMultiError(errors)
	}

	return nil
}

// GetResponseMultiError is an error wrapping multiple validation errors
// returned by GetResponse.ValidateAll() if the designated constraints aren't met.
type GetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetResponseMultiError) AllErrors() []error { return m }

// GetResponseValidationError is the validation error returned by
// GetResponse.Validate if the designated constraints aren't met.
type GetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetResponseValidationError) ErrorName() string { return "GetResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetResponseValidationError{}
