// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: kms/api/cmk/sessionmanager/oidcmapping/v1/oidcmapping.proto

package oidcmappingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// apply (create or update) the OIDC provider mapping for the given tenant
type ApplyOIDCMappingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	JwksUris      []string               `protobuf:"bytes,3,rep,name=jwks_uris,json=jwksUris,proto3" json:"jwks_uris,omitempty"`
	Audiences     []string               `protobuf:"bytes,4,rep,name=audiences,proto3" json:"audiences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyOIDCMappingRequest) Reset() {
	*x = ApplyOIDCMappingRequest{}
	mi := &file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyOIDCMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyOIDCMappingRequest) ProtoMessage() {}

func (x *ApplyOIDCMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyOIDCMappingRequest.ProtoReflect.Descriptor instead.
func (*ApplyOIDCMappingRequest) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyOIDCMappingRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ApplyOIDCMappingRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *ApplyOIDCMappingRequest) GetJwksUris() []string {
	if x != nil {
		return x.JwksUris
	}
	return nil
}

func (x *ApplyOIDCMappingRequest) GetAudiences() []string {
	if x != nil {
		return x.Audiences
	}
	return nil
}

type ApplyOIDCMappingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyOIDCMappingResponse) Reset() {
	*x = ApplyOIDCMappingResponse{}
	mi := &file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyOIDCMappingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyOIDCMappingResponse) ProtoMessage() {}

func (x *ApplyOIDCMappingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyOIDCMappingResponse.ProtoReflect.Descriptor instead.
func (*ApplyOIDCMappingResponse) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyOIDCMappingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyOIDCMappingResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// remove the OIDC provider mapping for the given tenant
type RemoveOIDCMappingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveOIDCMappingRequest) Reset() {
	*x = RemoveOIDCMappingRequest{}
	mi := &file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveOIDCMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOIDCMappingRequest) ProtoMessage() {}

func (x *RemoveOIDCMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOIDCMappingRequest.ProtoReflect.Descriptor instead.
func (*RemoveOIDCMappingRequest) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveOIDCMappingRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type RemoveOIDCMappingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveOIDCMappingResponse) Reset() {
	*x = RemoveOIDCMappingResponse{}
	mi := &file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveOIDCMappingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOIDCMappingResponse) ProtoMessage() {}

func (x *RemoveOIDCMappingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOIDCMappingResponse.ProtoReflect.Descriptor instead.
func (*RemoveOIDCMappingResponse) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveOIDCMappingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveOIDCMappingResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// block OIDC provider for the given tenant
type BlockOIDCMappingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockOIDCMappingRequest) Reset() {
	*x = BlockOIDCMappingRequest{}
	mi := &file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockOIDCMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockOIDCMappingRequest) ProtoMessage() {}

func (x *BlockOIDCMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockOIDCMappingRequest.ProtoReflect.Descriptor instead.
func (*BlockOIDCMappingRequest) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDescGZIP(), []int{4}
}

func (x *BlockOIDCMappingRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type BlockOIDCMappingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockOIDCMappingResponse) Reset() {
	*x = BlockOIDCMappingResponse{}
	mi := &file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockOIDCMappingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockOIDCMappingResponse) ProtoMessage() {}

func (x *BlockOIDCMappingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockOIDCMappingResponse.ProtoReflect.Descriptor instead.
func (*BlockOIDCMappingResponse) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDescGZIP(), []int{5}
}

func (x *BlockOIDCMappingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BlockOIDCMappingResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// unblock OIDC provider for the given tenant
type UnblockOIDCMappingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockOIDCMappingRequest) Reset() {
	*x = UnblockOIDCMappingRequest{}
	mi := &file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockOIDCMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockOIDCMappingRequest) ProtoMessage() {}

func (x *UnblockOIDCMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockOIDCMappingRequest.ProtoReflect.Descriptor instead.
func (*UnblockOIDCMappingRequest) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDescGZIP(), []int{6}
}

func (x *UnblockOIDCMappingRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type UnblockOIDCMappingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockOIDCMappingResponse) Reset() {
	*x = UnblockOIDCMappingResponse{}
	mi := &file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockOIDCMappingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockOIDCMappingResponse) ProtoMessage() {}

func (x *UnblockOIDCMappingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockOIDCMappingResponse.ProtoReflect.Descriptor instead.
func (*UnblockOIDCMappingResponse) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDescGZIP(), []int{7}
}

func (x *UnblockOIDCMappingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnblockOIDCMappingResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto protoreflect.FileDescriptor

const file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDesc = "" +
	"\n" +
	";kms/api/cmk/sessionmanager/oidcmapping/v1/oidcmapping.proto\x12)kms.api.cmk.sessionmanager.oidcmapping.v1\"\x89\x01\n" +
	"\x17ApplyOIDCMappingRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x1b\n" +
	"\tjwks_uris\x18\x03 \x03(\tR\bjwksUris\x12\x1c\n" +
	"\taudiences\x18\x04 \x03(\tR\taudiences\"_\n" +
	"\x18ApplyOIDCMappingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"7\n" +
	"\x18RemoveOIDCMappingRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"`\n" +
	"\x19RemoveOIDCMappingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"6\n" +
	"\x17BlockOIDCMappingRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"_\n" +
	"\x18BlockOIDCMappingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"8\n" +
	"\x19UnblockOIDCMappingRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"a\n" +
	"\x1aUnblockOIDCMappingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message2\x9d\x05\n" +
	"\x12OIDCMappingService\x12\x9d\x01\n" +
	"\x10ApplyOIDCMapping\x12B.kms.api.cmk.sessionmanager.oidcmapping.v1.ApplyOIDCMappingRequest\x1aC.kms.api.cmk.sessionmanager.oidcmapping.v1.ApplyOIDCMappingResponse\"\x00\x12\xa0\x01\n" +
	"\x11RemoveOIDCMapping\x12C.kms.api.cmk.sessionmanager.oidcmapping.v1.RemoveOIDCMappingRequest\x1aD.kms.api.cmk.sessionmanager.oidcmapping.v1.RemoveOIDCMappingResponse\"\x00\x12\x9d\x01\n" +
	"\x10BlockOIDCMapping\x12B.kms.api.cmk.sessionmanager.oidcmapping.v1.BlockOIDCMappingRequest\x1aC.kms.api.cmk.sessionmanager.oidcmapping.v1.BlockOIDCMappingResponse\"\x00\x12\xa3\x01\n" +
	"\x12UnblockOIDCMapping\x12D.kms.api.cmk.sessionmanager.oidcmapping.v1.UnblockOIDCMappingRequest\x1aE.kms.api.cmk.sessionmanager.oidcmapping.v1.UnblockOIDCMappingResponse\"\x00B\xe6\x02\n" +
	"-com.kms.api.cmk.sessionmanager.oidcmapping.v1B\x10OidcmappingProtoP\x01ZXgithub.com/openkcm/api-sdk/proto/kms/api/cmk/sessionmanager/oidcmapping/v1;oidcmappingv1\xa2\x02\x05KACSO\xaa\x02)Kms.Api.Cmk.Sessionmanager.Oidcmapping.V1\xca\x02)Kms\\Api\\Cmk\\Sessionmanager\\Oidcmapping\\V1\xe2\x025Kms\\Api\\Cmk\\Sessionmanager\\Oidcmapping\\V1\\GPBMetadata\xea\x02.Kms::Api::Cmk::Sessionmanager::Oidcmapping::V1b\x06proto3"

var (
	file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDescOnce sync.Once
	file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDescData []byte
)

func file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDescGZIP() []byte {
	file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDescOnce.Do(func() {
		file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDesc), len(file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDesc)))
	})
	return file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDescData
}

var file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_goTypes = []any{
	(*ApplyOIDCMappingRequest)(nil),    // 0: kms.api.cmk.sessionmanager.oidcmapping.v1.ApplyOIDCMappingRequest
	(*ApplyOIDCMappingResponse)(nil),   // 1: kms.api.cmk.sessionmanager.oidcmapping.v1.ApplyOIDCMappingResponse
	(*RemoveOIDCMappingRequest)(nil),   // 2: kms.api.cmk.sessionmanager.oidcmapping.v1.RemoveOIDCMappingRequest
	(*RemoveOIDCMappingResponse)(nil),  // 3: kms.api.cmk.sessionmanager.oidcmapping.v1.RemoveOIDCMappingResponse
	(*BlockOIDCMappingRequest)(nil),    // 4: kms.api.cmk.sessionmanager.oidcmapping.v1.BlockOIDCMappingRequest
	(*BlockOIDCMappingResponse)(nil),   // 5: kms.api.cmk.sessionmanager.oidcmapping.v1.BlockOIDCMappingResponse
	(*UnblockOIDCMappingRequest)(nil),  // 6: kms.api.cmk.sessionmanager.oidcmapping.v1.UnblockOIDCMappingRequest
	(*UnblockOIDCMappingResponse)(nil), // 7: kms.api.cmk.sessionmanager.oidcmapping.v1.UnblockOIDCMappingResponse
}
var file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_depIdxs = []int32{
	0, // 0: kms.api.cmk.sessionmanager.oidcmapping.v1.OIDCMappingService.ApplyOIDCMapping:input_type -> kms.api.cmk.sessionmanager.oidcmapping.v1.ApplyOIDCMappingRequest
	2, // 1: kms.api.cmk.sessionmanager.oidcmapping.v1.OIDCMappingService.RemoveOIDCMapping:input_type -> kms.api.cmk.sessionmanager.oidcmapping.v1.RemoveOIDCMappingRequest
	4, // 2: kms.api.cmk.sessionmanager.oidcmapping.v1.OIDCMappingService.BlockOIDCMapping:input_type -> kms.api.cmk.sessionmanager.oidcmapping.v1.BlockOIDCMappingRequest
	6, // 3: kms.api.cmk.sessionmanager.oidcmapping.v1.OIDCMappingService.UnblockOIDCMapping:input_type -> kms.api.cmk.sessionmanager.oidcmapping.v1.UnblockOIDCMappingRequest
	1, // 4: kms.api.cmk.sessionmanager.oidcmapping.v1.OIDCMappingService.ApplyOIDCMapping:output_type -> kms.api.cmk.sessionmanager.oidcmapping.v1.ApplyOIDCMappingResponse
	3, // 5: kms.api.cmk.sessionmanager.oidcmapping.v1.OIDCMappingService.RemoveOIDCMapping:output_type -> kms.api.cmk.sessionmanager.oidcmapping.v1.RemoveOIDCMappingResponse
	5, // 6: kms.api.cmk.sessionmanager.oidcmapping.v1.OIDCMappingService.BlockOIDCMapping:output_type -> kms.api.cmk.sessionmanager.oidcmapping.v1.BlockOIDCMappingResponse
	7, // 7: kms.api.cmk.sessionmanager.oidcmapping.v1.OIDCMappingService.UnblockOIDCMapping:output_type -> kms.api.cmk.sessionmanager.oidcmapping.v1.UnblockOIDCMappingResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_init() }
func file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_init() {
	if File_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto != nil {
		return
	}
	file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[1].OneofWrappers = []any{}
	file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[3].OneofWrappers = []any{}
	file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[5].OneofWrappers = []any{}
	file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDesc), len(file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_goTypes,
		DependencyIndexes: file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_depIdxs,
		MessageInfos:      file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_msgTypes,
	}.Build()
	File_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto = out.File
	file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_goTypes = nil
	file_kms_api_cmk_sessionmanager_oidcmapping_v1_oidcmapping_proto_depIdxs = nil
}
