// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: kms/api/cmk/registry/auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthStatus int32

const (
	AuthStatus_UNSPECIFIED    AuthStatus = 0
	AuthStatus_APPLIED        AuthStatus = 1
	AuthStatus_APPLYING       AuthStatus = 2
	AuthStatus_APPLYING_ERROR AuthStatus = 3
	AuthStatus_REMOVING       AuthStatus = 4
	AuthStatus_REMOVING_ERROR AuthStatus = 5
	AuthStatus_REMOVED        AuthStatus = 6
)

// Enum value maps for AuthStatus.
var (
	AuthStatus_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "APPLIED",
		2: "APPLYING",
		3: "APPLYING_ERROR",
		4: "REMOVING",
		5: "REMOVING_ERROR",
		6: "REMOVED",
	}
	AuthStatus_value = map[string]int32{
		"UNSPECIFIED":    0,
		"APPLIED":        1,
		"APPLYING":       2,
		"APPLYING_ERROR": 3,
		"REMOVING":       4,
		"REMOVING_ERROR": 5,
		"REMOVED":        6,
	}
)

func (x AuthStatus) Enum() *AuthStatus {
	p := new(AuthStatus)
	*p = x
	return p
}

func (x AuthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_kms_api_cmk_registry_auth_v1_auth_proto_enumTypes[0].Descriptor()
}

func (AuthStatus) Type() protoreflect.EnumType {
	return &file_kms_api_cmk_registry_auth_v1_auth_proto_enumTypes[0]
}

func (x AuthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthStatus.Descriptor instead.
func (AuthStatus) EnumDescriptor() ([]byte, []int) {
	return file_kms_api_cmk_registry_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

type AuthAction int32

const (
	AuthAction_ACTION_UNSPECIFIED AuthAction = 0
	AuthAction_ACTION_APPLY_AUTH  AuthAction = 1
)

// Enum value maps for AuthAction.
var (
	AuthAction_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_APPLY_AUTH",
	}
	AuthAction_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_APPLY_AUTH":  1,
	}
)

func (x AuthAction) Enum() *AuthAction {
	p := new(AuthAction)
	*p = x
	return p
}

func (x AuthAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthAction) Descriptor() protoreflect.EnumDescriptor {
	return file_kms_api_cmk_registry_auth_v1_auth_proto_enumTypes[1].Descriptor()
}

func (AuthAction) Type() protoreflect.EnumType {
	return &file_kms_api_cmk_registry_auth_v1_auth_proto_enumTypes[1]
}

func (x AuthAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthAction.Descriptor instead.
func (AuthAction) EnumDescriptor() ([]byte, []int) {
	return file_kms_api_cmk_registry_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        AuthStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=kms.api.cmk.registry.auth.v1.AuthStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_kms_api_cmk_registry_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_registry_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_registry_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *Auth) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Auth) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Auth) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Auth) GetStatus() AuthStatus {
	if x != nil {
		return x.Status
	}
	return AuthStatus_UNSPECIFIED
}

func (x *Auth) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Auth) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Auth) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ApplyAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyAuthRequest) Reset() {
	*x = ApplyAuthRequest{}
	mi := &file_kms_api_cmk_registry_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyAuthRequest) ProtoMessage() {}

func (x *ApplyAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_registry_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyAuthRequest.ProtoReflect.Descriptor instead.
func (*ApplyAuthRequest) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_registry_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyAuthRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ApplyAuthRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ApplyAuthRequest) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type ApplyAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyAuthResponse) Reset() {
	*x = ApplyAuthResponse{}
	mi := &file_kms_api_cmk_registry_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyAuthResponse) ProtoMessage() {}

func (x *ApplyAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_registry_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyAuthResponse.ProtoReflect.Descriptor instead.
func (*ApplyAuthResponse) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_registry_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyAuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthRequest) Reset() {
	*x = GetAuthRequest{}
	mi := &file_kms_api_cmk_registry_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthRequest) ProtoMessage() {}

func (x *GetAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_registry_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthRequest.ProtoReflect.Descriptor instead.
func (*GetAuthRequest) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_registry_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuthRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Auth                  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthResponse) Reset() {
	*x = GetAuthResponse{}
	mi := &file_kms_api_cmk_registry_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthResponse) ProtoMessage() {}

func (x *GetAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_registry_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthResponse.ProtoReflect.Descriptor instead.
func (*GetAuthResponse) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_registry_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *GetAuthResponse) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

type RemoveAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAuthRequest) Reset() {
	*x = RemoveAuthRequest{}
	mi := &file_kms_api_cmk_registry_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAuthRequest) ProtoMessage() {}

func (x *RemoveAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_registry_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAuthRequest.ProtoReflect.Descriptor instead.
func (*RemoveAuthRequest) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_registry_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveAuthRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type RemoveAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAuthResponse) Reset() {
	*x = RemoveAuthResponse{}
	mi := &file_kms_api_cmk_registry_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAuthResponse) ProtoMessage() {}

func (x *RemoveAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_registry_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAuthResponse.ProtoReflect.Descriptor instead.
func (*RemoveAuthResponse) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_registry_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveAuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_kms_api_cmk_registry_auth_v1_auth_proto protoreflect.FileDescriptor

const file_kms_api_cmk_registry_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"'kms/api/cmk/registry/auth/v1/auth.proto\x12\x1ckms.api.cmk.registry.auth.v1\"\xef\x02\n" +
	"\x04Auth\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12R\n" +
	"\n" +
	"properties\x18\x03 \x03(\v22.kms.api.cmk.registry.auth.v1.Auth.PropertiesEntryR\n" +
	"properties\x12@\n" +
	"\x06status\x18\x04 \x01(\x0e2(.kms.api.cmk.registry.auth.v1.AuthStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe2\x01\n" +
	"\x10ApplyAuthRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12^\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2>.kms.api.cmk.registry.auth.v1.ApplyAuthRequest.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x11ApplyAuthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x0eGetAuthRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"I\n" +
	"\x0fGetAuthResponse\x126\n" +
	"\x04auth\x18\x01 \x01(\v2\".kms.api.cmk.registry.auth.v1.AuthR\x04auth\"0\n" +
	"\x11RemoveAuthRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\".\n" +
	"\x12RemoveAuthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*{\n" +
	"\n" +
	"AuthStatus\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aAPPLIED\x10\x01\x12\f\n" +
	"\bAPPLYING\x10\x02\x12\x12\n" +
	"\x0eAPPLYING_ERROR\x10\x03\x12\f\n" +
	"\bREMOVING\x10\x04\x12\x12\n" +
	"\x0eREMOVING_ERROR\x10\x05\x12\v\n" +
	"\aREMOVED\x10\x06*;\n" +
	"\n" +
	"AuthAction\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACTION_APPLY_AUTH\x10\x012\xd6\x02\n" +
	"\aService\x12n\n" +
	"\tApplyAuth\x12..kms.api.cmk.registry.auth.v1.ApplyAuthRequest\x1a/.kms.api.cmk.registry.auth.v1.ApplyAuthResponse\"\x00\x12h\n" +
	"\aGetAuth\x12,.kms.api.cmk.registry.auth.v1.GetAuthRequest\x1a-.kms.api.cmk.registry.auth.v1.GetAuthResponse\"\x00\x12q\n" +
	"\n" +
	"RemoveAuth\x12/.kms.api.cmk.registry.auth.v1.RemoveAuthRequest\x1a0.kms.api.cmk.registry.auth.v1.RemoveAuthResponse\"\x00B\x8a\x02\n" +
	" com.kms.api.cmk.registry.auth.v1B\tAuthProtoP\x01ZDgithub.com/openkcm/api-sdk/proto/kms/api/cmk/registry/auth/v1;authv1\xa2\x02\x05KACRA\xaa\x02\x1cKms.Api.Cmk.Registry.Auth.V1\xca\x02\x1cKms\\Api\\Cmk\\Registry\\Auth\\V1\xe2\x02(Kms\\Api\\Cmk\\Registry\\Auth\\V1\\GPBMetadata\xea\x02!Kms::Api::Cmk::Registry::Auth::V1b\x06proto3"

var (
	file_kms_api_cmk_registry_auth_v1_auth_proto_rawDescOnce sync.Once
	file_kms_api_cmk_registry_auth_v1_auth_proto_rawDescData []byte
)

func file_kms_api_cmk_registry_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_kms_api_cmk_registry_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_kms_api_cmk_registry_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kms_api_cmk_registry_auth_v1_auth_proto_rawDesc), len(file_kms_api_cmk_registry_auth_v1_auth_proto_rawDesc)))
	})
	return file_kms_api_cmk_registry_auth_v1_auth_proto_rawDescData
}

var file_kms_api_cmk_registry_auth_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kms_api_cmk_registry_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_kms_api_cmk_registry_auth_v1_auth_proto_goTypes = []any{
	(AuthStatus)(0),            // 0: kms.api.cmk.registry.auth.v1.AuthStatus
	(AuthAction)(0),            // 1: kms.api.cmk.registry.auth.v1.AuthAction
	(*Auth)(nil),               // 2: kms.api.cmk.registry.auth.v1.Auth
	(*ApplyAuthRequest)(nil),   // 3: kms.api.cmk.registry.auth.v1.ApplyAuthRequest
	(*ApplyAuthResponse)(nil),  // 4: kms.api.cmk.registry.auth.v1.ApplyAuthResponse
	(*GetAuthRequest)(nil),     // 5: kms.api.cmk.registry.auth.v1.GetAuthRequest
	(*GetAuthResponse)(nil),    // 6: kms.api.cmk.registry.auth.v1.GetAuthResponse
	(*RemoveAuthRequest)(nil),  // 7: kms.api.cmk.registry.auth.v1.RemoveAuthRequest
	(*RemoveAuthResponse)(nil), // 8: kms.api.cmk.registry.auth.v1.RemoveAuthResponse
	nil,                        // 9: kms.api.cmk.registry.auth.v1.Auth.PropertiesEntry
	nil,                        // 10: kms.api.cmk.registry.auth.v1.ApplyAuthRequest.PropertiesEntry
}
var file_kms_api_cmk_registry_auth_v1_auth_proto_depIdxs = []int32{
	9,  // 0: kms.api.cmk.registry.auth.v1.Auth.properties:type_name -> kms.api.cmk.registry.auth.v1.Auth.PropertiesEntry
	0,  // 1: kms.api.cmk.registry.auth.v1.Auth.status:type_name -> kms.api.cmk.registry.auth.v1.AuthStatus
	10, // 2: kms.api.cmk.registry.auth.v1.ApplyAuthRequest.properties:type_name -> kms.api.cmk.registry.auth.v1.ApplyAuthRequest.PropertiesEntry
	2,  // 3: kms.api.cmk.registry.auth.v1.GetAuthResponse.auth:type_name -> kms.api.cmk.registry.auth.v1.Auth
	3,  // 4: kms.api.cmk.registry.auth.v1.Service.ApplyAuth:input_type -> kms.api.cmk.registry.auth.v1.ApplyAuthRequest
	5,  // 5: kms.api.cmk.registry.auth.v1.Service.GetAuth:input_type -> kms.api.cmk.registry.auth.v1.GetAuthRequest
	7,  // 6: kms.api.cmk.registry.auth.v1.Service.RemoveAuth:input_type -> kms.api.cmk.registry.auth.v1.RemoveAuthRequest
	4,  // 7: kms.api.cmk.registry.auth.v1.Service.ApplyAuth:output_type -> kms.api.cmk.registry.auth.v1.ApplyAuthResponse
	6,  // 8: kms.api.cmk.registry.auth.v1.Service.GetAuth:output_type -> kms.api.cmk.registry.auth.v1.GetAuthResponse
	8,  // 9: kms.api.cmk.registry.auth.v1.Service.RemoveAuth:output_type -> kms.api.cmk.registry.auth.v1.RemoveAuthResponse
	7,  // [7:10] is the sub-list for method output_type
	4,  // [4:7] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_kms_api_cmk_registry_auth_v1_auth_proto_init() }
func file_kms_api_cmk_registry_auth_v1_auth_proto_init() {
	if File_kms_api_cmk_registry_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kms_api_cmk_registry_auth_v1_auth_proto_rawDesc), len(file_kms_api_cmk_registry_auth_v1_auth_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kms_api_cmk_registry_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_kms_api_cmk_registry_auth_v1_auth_proto_depIdxs,
		EnumInfos:         file_kms_api_cmk_registry_auth_v1_auth_proto_enumTypes,
		MessageInfos:      file_kms_api_cmk_registry_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_kms_api_cmk_registry_auth_v1_auth_proto = out.File
	file_kms_api_cmk_registry_auth_v1_auth_proto_goTypes = nil
	file_kms_api_cmk_registry_auth_v1_auth_proto_depIdxs = nil
}
