// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: kms/api/cmk/sessionmanager/oidcprovider/v1/oidcprovider.proto

package oidcproviderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// get the OIDC provider details for the given issuer
type GetOIDCProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOIDCProviderRequest) Reset() {
	*x = GetOIDCProviderRequest{}
	mi := &file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOIDCProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOIDCProviderRequest) ProtoMessage() {}

func (x *GetOIDCProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOIDCProviderRequest.ProtoReflect.Descriptor instead.
func (*GetOIDCProviderRequest) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_rawDescGZIP(), []int{0}
}

func (x *GetOIDCProviderRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

type GetOIDCProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	JwksUris      []string               `protobuf:"bytes,2,rep,name=jwks_uris,json=jwksUris,proto3" json:"jwks_uris,omitempty"`
	Audiences     []string               `protobuf:"bytes,3,rep,name=audiences,proto3" json:"audiences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOIDCProviderResponse) Reset() {
	*x = GetOIDCProviderResponse{}
	mi := &file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOIDCProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOIDCProviderResponse) ProtoMessage() {}

func (x *GetOIDCProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOIDCProviderResponse.ProtoReflect.Descriptor instead.
func (*GetOIDCProviderResponse) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_rawDescGZIP(), []int{1}
}

func (x *GetOIDCProviderResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *GetOIDCProviderResponse) GetJwksUris() []string {
	if x != nil {
		return x.JwksUris
	}
	return nil
}

func (x *GetOIDCProviderResponse) GetAudiences() []string {
	if x != nil {
		return x.Audiences
	}
	return nil
}

var File_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto protoreflect.FileDescriptor

const file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_rawDesc = "" +
	"\n" +
	"=kms/api/cmk/sessionmanager/oidcprovider/v1/oidcprovider.proto\x12*kms.api.cmk.sessionmanager.oidcprovider.v1\"0\n" +
	"\x16GetOIDCProviderRequest\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\"l\n" +
	"\x17GetOIDCProviderResponse\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x1b\n" +
	"\tjwks_uris\x18\x02 \x03(\tR\bjwksUris\x12\x1c\n" +
	"\taudiences\x18\x03 \x03(\tR\taudiences2\xb4\x01\n" +
	"\x13OIDCProviderService\x12\x9c\x01\n" +
	"\x0fGetOIDCProvider\x12B.kms.api.cmk.sessionmanager.oidcprovider.v1.GetOIDCProviderRequest\x1aC.kms.api.cmk.sessionmanager.oidcprovider.v1.GetOIDCProviderResponse\"\x00B\xee\x02\n" +
	".com.kms.api.cmk.sessionmanager.oidcprovider.v1B\x11OidcproviderProtoP\x01ZZgithub.com/openkcm/api-sdk/proto/kms/api/cmk/sessionmanager/oidcprovider/v1;oidcproviderv1\xa2\x02\x05KACSO\xaa\x02*Kms.Api.Cmk.Sessionmanager.Oidcprovider.V1\xca\x02*Kms\\Api\\Cmk\\Sessionmanager\\Oidcprovider\\V1\xe2\x026Kms\\Api\\Cmk\\Sessionmanager\\Oidcprovider\\V1\\GPBMetadata\xea\x02/Kms::Api::Cmk::Sessionmanager::Oidcprovider::V1b\x06proto3"

var (
	file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_rawDescOnce sync.Once
	file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_rawDescData []byte
)

func file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_rawDescGZIP() []byte {
	file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_rawDescOnce.Do(func() {
		file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_rawDesc), len(file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_rawDesc)))
	})
	return file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_rawDescData
}

var file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_goTypes = []any{
	(*GetOIDCProviderRequest)(nil),  // 0: kms.api.cmk.sessionmanager.oidcprovider.v1.GetOIDCProviderRequest
	(*GetOIDCProviderResponse)(nil), // 1: kms.api.cmk.sessionmanager.oidcprovider.v1.GetOIDCProviderResponse
}
var file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_depIdxs = []int32{
	0, // 0: kms.api.cmk.sessionmanager.oidcprovider.v1.OIDCProviderService.GetOIDCProvider:input_type -> kms.api.cmk.sessionmanager.oidcprovider.v1.GetOIDCProviderRequest
	1, // 1: kms.api.cmk.sessionmanager.oidcprovider.v1.OIDCProviderService.GetOIDCProvider:output_type -> kms.api.cmk.sessionmanager.oidcprovider.v1.GetOIDCProviderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_init() }
func file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_init() {
	if File_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_rawDesc), len(file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_goTypes,
		DependencyIndexes: file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_depIdxs,
		MessageInfos:      file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_msgTypes,
	}.Build()
	File_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto = out.File
	file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_goTypes = nil
	file_kms_api_cmk_sessionmanager_oidcprovider_v1_oidcprovider_proto_depIdxs = nil
}
