// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: kms/api/cmk/sessionmanager/oidcprovider/v1/oidcprovider.proto

package oidcproviderv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OIDCProviderService_GetOIDCProvider_FullMethodName = "/kms.api.cmk.sessionmanager.oidcprovider.v1.OIDCProviderService/GetOIDCProvider"
)

// OIDCProviderServiceClient is the client API for OIDCProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OIDCProviderServiceClient interface {
	GetOIDCProvider(ctx context.Context, in *GetOIDCProviderRequest, opts ...grpc.CallOption) (*GetOIDCProviderResponse, error)
}

type oIDCProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOIDCProviderServiceClient(cc grpc.ClientConnInterface) OIDCProviderServiceClient {
	return &oIDCProviderServiceClient{cc}
}

func (c *oIDCProviderServiceClient) GetOIDCProvider(ctx context.Context, in *GetOIDCProviderRequest, opts ...grpc.CallOption) (*GetOIDCProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOIDCProviderResponse)
	err := c.cc.Invoke(ctx, OIDCProviderService_GetOIDCProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OIDCProviderServiceServer is the server API for OIDCProviderService service.
// All implementations must embed UnimplementedOIDCProviderServiceServer
// for forward compatibility.
type OIDCProviderServiceServer interface {
	GetOIDCProvider(context.Context, *GetOIDCProviderRequest) (*GetOIDCProviderResponse, error)
	mustEmbedUnimplementedOIDCProviderServiceServer()
}

// UnimplementedOIDCProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOIDCProviderServiceServer struct{}

func (UnimplementedOIDCProviderServiceServer) GetOIDCProvider(context.Context, *GetOIDCProviderRequest) (*GetOIDCProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOIDCProvider not implemented")
}
func (UnimplementedOIDCProviderServiceServer) mustEmbedUnimplementedOIDCProviderServiceServer() {}
func (UnimplementedOIDCProviderServiceServer) testEmbeddedByValue()                             {}

// UnsafeOIDCProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OIDCProviderServiceServer will
// result in compilation errors.
type UnsafeOIDCProviderServiceServer interface {
	mustEmbedUnimplementedOIDCProviderServiceServer()
}

func RegisterOIDCProviderServiceServer(s grpc.ServiceRegistrar, srv OIDCProviderServiceServer) {
	// If the following call pancis, it indicates UnimplementedOIDCProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OIDCProviderService_ServiceDesc, srv)
}

func _OIDCProviderService_GetOIDCProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOIDCProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OIDCProviderServiceServer).GetOIDCProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OIDCProviderService_GetOIDCProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OIDCProviderServiceServer).GetOIDCProvider(ctx, req.(*GetOIDCProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OIDCProviderService_ServiceDesc is the grpc.ServiceDesc for OIDCProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OIDCProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kms.api.cmk.sessionmanager.oidcprovider.v1.OIDCProviderService",
	HandlerType: (*OIDCProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOIDCProvider",
			Handler:    _OIDCProviderService_GetOIDCProvider_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kms/api/cmk/sessionmanager/oidcprovider/v1/oidcprovider.proto",
}
