// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kms/api/cmk/registry/tenant/v1/tenant.proto

package tenantv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Tenant with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Tenant) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Tenant with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in TenantMultiError, or nil if none found.
func (m *Tenant) ValidateAll() error {
	return m.validate(true)
}

func (m *Tenant) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Region

	// no validation rules for OwnerId

	// no validation rules for OwnerType

	// no validation rules for Status

	// no validation rules for StatusUpdatedAt

	// no validation rules for Role

	// no validation rules for UpdatedAt

	// no validation rules for CreatedAt

	// no validation rules for Labels

	if len(errors) > 0 {
		return TenantMultiError(errors)
	}

	return nil
}

// TenantMultiError is an error wrapping multiple validation errors returned by
// Tenant.ValidateAll() if the designated constraints aren't met.
type TenantMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TenantMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TenantMultiError) AllErrors() []error { return m }

// TenantValidationError is the validation error returned by Tenant.Validate if
// the designated constraints aren't met.
type TenantValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TenantValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TenantValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TenantValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TenantValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TenantValidationError) ErrorName() string { return "TenantValidationError" }

// Error satisfies the builtin error interface
func (e TenantValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTenant.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TenantValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TenantValidationError{}

// Validate checks the field values on RegisterTenantRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterTenantRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterTenantRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterTenantRequestMultiError, or nil if none found.
func (m *RegisterTenantRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterTenantRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Id

	// no validation rules for Region

	// no validation rules for OwnerId

	// no validation rules for OwnerType

	// no validation rules for Role

	// no validation rules for Labels

	if len(errors) > 0 {
		return RegisterTenantRequestMultiError(errors)
	}

	return nil
}

// RegisterTenantRequestMultiError is an error wrapping multiple validation
// errors returned by RegisterTenantRequest.ValidateAll() if the designated
// constraints aren't met.
type RegisterTenantRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterTenantRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterTenantRequestMultiError) AllErrors() []error { return m }

// RegisterTenantRequestValidationError is the validation error returned by
// RegisterTenantRequest.Validate if the designated constraints aren't met.
type RegisterTenantRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterTenantRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterTenantRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterTenantRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterTenantRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterTenantRequestValidationError) ErrorName() string {
	return "RegisterTenantRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterTenantRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterTenantRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterTenantRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterTenantRequestValidationError{}

// Validate checks the field values on RegisterTenantResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterTenantResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterTenantResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterTenantResponseMultiError, or nil if none found.
func (m *RegisterTenantResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterTenantResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return RegisterTenantResponseMultiError(errors)
	}

	return nil
}

// RegisterTenantResponseMultiError is an error wrapping multiple validation
// errors returned by RegisterTenantResponse.ValidateAll() if the designated
// constraints aren't met.
type RegisterTenantResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterTenantResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterTenantResponseMultiError) AllErrors() []error { return m }

// RegisterTenantResponseValidationError is the validation error returned by
// RegisterTenantResponse.Validate if the designated constraints aren't met.
type RegisterTenantResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterTenantResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterTenantResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterTenantResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterTenantResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterTenantResponseValidationError) ErrorName() string {
	return "RegisterTenantResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterTenantResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterTenantResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterTenantResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterTenantResponseValidationError{}

// Validate checks the field values on ListTenantsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListTenantsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTenantsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTenantsRequestMultiError, or nil if none found.
func (m *ListTenantsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTenantsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Region

	// no validation rules for OwnerId

	// no validation rules for OwnerType

	// no validation rules for Limit

	// no validation rules for PageToken

	if len(errors) > 0 {
		return ListTenantsRequestMultiError(errors)
	}

	return nil
}

// ListTenantsRequestMultiError is an error wrapping multiple validation errors
// returned by ListTenantsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListTenantsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTenantsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTenantsRequestMultiError) AllErrors() []error { return m }

// ListTenantsRequestValidationError is the validation error returned by
// ListTenantsRequest.Validate if the designated constraints aren't met.
type ListTenantsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTenantsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTenantsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTenantsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTenantsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTenantsRequestValidationError) ErrorName() string {
	return "ListTenantsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListTenantsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTenantsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTenantsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTenantsRequestValidationError{}

// Validate checks the field values on ListTenantsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListTenantsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTenantsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTenantsResponseMultiError, or nil if none found.
func (m *ListTenantsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTenantsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTenants() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListTenantsResponseValidationError{
						field:  fmt.Sprintf("Tenants[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListTenantsResponseValidationError{
						field:  fmt.Sprintf("Tenants[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListTenantsResponseValidationError{
					field:  fmt.Sprintf("Tenants[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListTenantsResponseMultiError(errors)
	}

	return nil
}

// ListTenantsResponseMultiError is an error wrapping multiple validation
// errors returned by ListTenantsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListTenantsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTenantsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTenantsResponseMultiError) AllErrors() []error { return m }

// ListTenantsResponseValidationError is the validation error returned by
// ListTenantsResponse.Validate if the designated constraints aren't met.
type ListTenantsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTenantsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTenantsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTenantsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTenantsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTenantsResponseValidationError) ErrorName() string {
	return "ListTenantsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListTenantsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTenantsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTenantsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTenantsResponseValidationError{}

// Validate checks the field values on BlockTenantRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BlockTenantRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BlockTenantRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BlockTenantRequestMultiError, or nil if none found.
func (m *BlockTenantRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BlockTenantRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return BlockTenantRequestMultiError(errors)
	}

	return nil
}

// BlockTenantRequestMultiError is an error wrapping multiple validation errors
// returned by BlockTenantRequest.ValidateAll() if the designated constraints
// aren't met.
type BlockTenantRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BlockTenantRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BlockTenantRequestMultiError) AllErrors() []error { return m }

// BlockTenantRequestValidationError is the validation error returned by
// BlockTenantRequest.Validate if the designated constraints aren't met.
type BlockTenantRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BlockTenantRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BlockTenantRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BlockTenantRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BlockTenantRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BlockTenantRequestValidationError) ErrorName() string {
	return "BlockTenantRequestValidationError"
}

// Error satisfies the builtin error interface
func (e BlockTenantRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBlockTenantRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BlockTenantRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BlockTenantRequestValidationError{}

// Validate checks the field values on BlockTenantResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BlockTenantResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BlockTenantResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BlockTenantResponseMultiError, or nil if none found.
func (m *BlockTenantResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BlockTenantResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return BlockTenantResponseMultiError(errors)
	}

	return nil
}

// BlockTenantResponseMultiError is an error wrapping multiple validation
// errors returned by BlockTenantResponse.ValidateAll() if the designated
// constraints aren't met.
type BlockTenantResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BlockTenantResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BlockTenantResponseMultiError) AllErrors() []error { return m }

// BlockTenantResponseValidationError is the validation error returned by
// BlockTenantResponse.Validate if the designated constraints aren't met.
type BlockTenantResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BlockTenantResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BlockTenantResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BlockTenantResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BlockTenantResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BlockTenantResponseValidationError) ErrorName() string {
	return "BlockTenantResponseValidationError"
}

// Error satisfies the builtin error interface
func (e BlockTenantResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBlockTenantResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BlockTenantResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BlockTenantResponseValidationError{}

// Validate checks the field values on UnblockTenantRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UnblockTenantRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UnblockTenantRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UnblockTenantRequestMultiError, or nil if none found.
func (m *UnblockTenantRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UnblockTenantRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return UnblockTenantRequestMultiError(errors)
	}

	return nil
}

// UnblockTenantRequestMultiError is an error wrapping multiple validation
// errors returned by UnblockTenantRequest.ValidateAll() if the designated
// constraints aren't met.
type UnblockTenantRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UnblockTenantRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UnblockTenantRequestMultiError) AllErrors() []error { return m }

// UnblockTenantRequestValidationError is the validation error returned by
// UnblockTenantRequest.Validate if the designated constraints aren't met.
type UnblockTenantRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UnblockTenantRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UnblockTenantRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UnblockTenantRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UnblockTenantRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UnblockTenantRequestValidationError) ErrorName() string {
	return "UnblockTenantRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UnblockTenantRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUnblockTenantRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UnblockTenantRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UnblockTenantRequestValidationError{}

// Validate checks the field values on UnblockTenantResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UnblockTenantResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UnblockTenantResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UnblockTenantResponseMultiError, or nil if none found.
func (m *UnblockTenantResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UnblockTenantResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return UnblockTenantResponseMultiError(errors)
	}

	return nil
}

// UnblockTenantResponseMultiError is an error wrapping multiple validation
// errors returned by UnblockTenantResponse.ValidateAll() if the designated
// constraints aren't met.
type UnblockTenantResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UnblockTenantResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UnblockTenantResponseMultiError) AllErrors() []error { return m }

// UnblockTenantResponseValidationError is the validation error returned by
// UnblockTenantResponse.Validate if the designated constraints aren't met.
type UnblockTenantResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UnblockTenantResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UnblockTenantResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UnblockTenantResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UnblockTenantResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UnblockTenantResponseValidationError) ErrorName() string {
	return "UnblockTenantResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UnblockTenantResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUnblockTenantResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UnblockTenantResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UnblockTenantResponseValidationError{}

// Validate checks the field values on TerminateTenantRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TerminateTenantRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TerminateTenantRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TerminateTenantRequestMultiError, or nil if none found.
func (m *TerminateTenantRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TerminateTenantRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return TerminateTenantRequestMultiError(errors)
	}

	return nil
}

// TerminateTenantRequestMultiError is an error wrapping multiple validation
// errors returned by TerminateTenantRequest.ValidateAll() if the designated
// constraints aren't met.
type TerminateTenantRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TerminateTenantRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TerminateTenantRequestMultiError) AllErrors() []error { return m }

// TerminateTenantRequestValidationError is the validation error returned by
// TerminateTenantRequest.Validate if the designated constraints aren't met.
type TerminateTenantRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TerminateTenantRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TerminateTenantRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TerminateTenantRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TerminateTenantRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TerminateTenantRequestValidationError) ErrorName() string {
	return "TerminateTenantRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TerminateTenantRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTerminateTenantRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TerminateTenantRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TerminateTenantRequestValidationError{}

// Validate checks the field values on TerminateTenantResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TerminateTenantResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TerminateTenantResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TerminateTenantResponseMultiError, or nil if none found.
func (m *TerminateTenantResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TerminateTenantResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return TerminateTenantResponseMultiError(errors)
	}

	return nil
}

// TerminateTenantResponseMultiError is an error wrapping multiple validation
// errors returned by TerminateTenantResponse.ValidateAll() if the designated
// constraints aren't met.
type TerminateTenantResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TerminateTenantResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TerminateTenantResponseMultiError) AllErrors() []error { return m }

// TerminateTenantResponseValidationError is the validation error returned by
// TerminateTenantResponse.Validate if the designated constraints aren't met.
type TerminateTenantResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TerminateTenantResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TerminateTenantResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TerminateTenantResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TerminateTenantResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TerminateTenantResponseValidationError) ErrorName() string {
	return "TerminateTenantResponseValidationError"
}

// Error satisfies the builtin error interface
func (e TerminateTenantResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTerminateTenantResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TerminateTenantResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TerminateTenantResponseValidationError{}
