// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: kms/api/cmk/registry/tenant_config/v1/tenant_config.proto

package tenantconfigv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TenantConfigStatus int32

const (
	TenantConfigStatus_TENANT_CONFIG_STATUS_UNSPECIFIED    TenantConfigStatus = 0
	TenantConfigStatus_TENANT_CONFIG_STATUS_UPDATING       TenantConfigStatus = 1
	TenantConfigStatus_TENANT_CONFIG_STATUS_UPDATING_ERROR TenantConfigStatus = 2
	TenantConfigStatus_TENANT_CONFIG_STATUS_ACTIVE         TenantConfigStatus = 3
)

// Enum value maps for TenantConfigStatus.
var (
	TenantConfigStatus_name = map[int32]string{
		0: "TENANT_CONFIG_STATUS_UNSPECIFIED",
		1: "TENANT_CONFIG_STATUS_UPDATING",
		2: "TENANT_CONFIG_STATUS_UPDATING_ERROR",
		3: "TENANT_CONFIG_STATUS_ACTIVE",
	}
	TenantConfigStatus_value = map[string]int32{
		"TENANT_CONFIG_STATUS_UNSPECIFIED":    0,
		"TENANT_CONFIG_STATUS_UPDATING":       1,
		"TENANT_CONFIG_STATUS_UPDATING_ERROR": 2,
		"TENANT_CONFIG_STATUS_ACTIVE":         3,
	}
)

func (x TenantConfigStatus) Enum() *TenantConfigStatus {
	p := new(TenantConfigStatus)
	*p = x
	return p
}

func (x TenantConfigStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TenantConfigStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_enumTypes[0].Descriptor()
}

func (TenantConfigStatus) Type() protoreflect.EnumType {
	return &file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_enumTypes[0]
}

func (x TenantConfigStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TenantConfigStatus.Descriptor instead.
func (TenantConfigStatus) EnumDescriptor() ([]byte, []int) {
	return file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDescGZIP(), []int{0}
}

// TenantConfigAction defines the orbital job types used by the registry service
// to drive tenant config reconciliation.
type TenantConfigAction int32

const (
	TenantConfigAction_TENANT_CONFIG_ACTION_UNSPECIFIED TenantConfigAction = 0
	TenantConfigAction_TENANT_CONFIG_ACTION_UPDATE      TenantConfigAction = 1
)

// Enum value maps for TenantConfigAction.
var (
	TenantConfigAction_name = map[int32]string{
		0: "TENANT_CONFIG_ACTION_UNSPECIFIED",
		1: "TENANT_CONFIG_ACTION_UPDATE",
	}
	TenantConfigAction_value = map[string]int32{
		"TENANT_CONFIG_ACTION_UNSPECIFIED": 0,
		"TENANT_CONFIG_ACTION_UPDATE":      1,
	}
)

func (x TenantConfigAction) Enum() *TenantConfigAction {
	p := new(TenantConfigAction)
	*p = x
	return p
}

func (x TenantConfigAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TenantConfigAction) Descriptor() protoreflect.EnumDescriptor {
	return file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_enumTypes[1].Descriptor()
}

func (TenantConfigAction) Type() protoreflect.EnumType {
	return &file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_enumTypes[1]
}

func (x TenantConfigAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TenantConfigAction.Descriptor instead.
func (TenantConfigAction) EnumDescriptor() ([]byte, []int) {
	return file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDescGZIP(), []int{1}
}

// TenantConfigurationValues holds the user-settable tenant configuration overrides.
type TenantConfigurationValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of systems allowed per key configuration.
	// Default: system default (global limit).
	SystemLimit   *int32 `protobuf:"varint,1,opt,name=system_limit,json=systemLimit,proto3,oneof" json:"system_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantConfigurationValues) Reset() {
	*x = TenantConfigurationValues{}
	mi := &file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantConfigurationValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantConfigurationValues) ProtoMessage() {}

func (x *TenantConfigurationValues) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantConfigurationValues.ProtoReflect.Descriptor instead.
func (*TenantConfigurationValues) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDescGZIP(), []int{0}
}

func (x *TenantConfigurationValues) GetSystemLimit() int32 {
	if x != nil && x.SystemLimit != nil {
		return *x.SystemLimit
	}
	return 0
}

type GetTenantConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantConfigRequest) Reset() {
	*x = GetTenantConfigRequest{}
	mi := &file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantConfigRequest) ProtoMessage() {}

func (x *GetTenantConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantConfigRequest.ProtoReflect.Descriptor instead.
func (*GetTenantConfigRequest) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDescGZIP(), []int{1}
}

func (x *GetTenantConfigRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetTenantConfigResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	TenantId      string                     `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Values        *TenantConfigurationValues `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	Status        TenantConfigStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=kms.api.cmk.registry.tenant_config.v1.TenantConfigStatus" json:"status,omitempty"`
	ErrorMessage  string                     `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     string                     `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                     `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantConfigResponse) Reset() {
	*x = GetTenantConfigResponse{}
	mi := &file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantConfigResponse) ProtoMessage() {}

func (x *GetTenantConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantConfigResponse.ProtoReflect.Descriptor instead.
func (*GetTenantConfigResponse) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDescGZIP(), []int{2}
}

func (x *GetTenantConfigResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetTenantConfigResponse) GetValues() *TenantConfigurationValues {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *GetTenantConfigResponse) GetStatus() TenantConfigStatus {
	if x != nil {
		return x.Status
	}
	return TenantConfigStatus_TENANT_CONFIG_STATUS_UNSPECIFIED
}

func (x *GetTenantConfigResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetTenantConfigResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetTenantConfigResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UpdateTenantConfigRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	TenantId      string                     `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Values        *TenantConfigurationValues `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask     `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantConfigRequest) Reset() {
	*x = UpdateTenantConfigRequest{}
	mi := &file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantConfigRequest) ProtoMessage() {}

func (x *UpdateTenantConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantConfigRequest) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTenantConfigRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateTenantConfigRequest) GetValues() *TenantConfigurationValues {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *UpdateTenantConfigRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type UpdateTenantConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantConfigResponse) Reset() {
	*x = UpdateTenantConfigResponse{}
	mi := &file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantConfigResponse) ProtoMessage() {}

func (x *UpdateTenantConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateTenantConfigResponse) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDescGZIP(), []int{4}
}

var File_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto protoreflect.FileDescriptor

const file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDesc = "" +
	"\n" +
	"9kms/api/cmk/registry/tenant_config/v1/tenant_config.proto\x12%kms.api.cmk.registry.tenant_config.v1\x1a\x1bbuf/validate/validate.proto\x1a google/protobuf/field_mask.proto\"T\n" +
	"\x19TenantConfigurationValues\x12&\n" +
	"\fsystem_limit\x18\x01 \x01(\x05H\x00R\vsystemLimit\x88\x01\x01B\x0f\n" +
	"\r_system_limit\">\n" +
	"\x16GetTenantConfigRequest\x12$\n" +
	"\ttenant_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\btenantId\"\xc6\x02\n" +
	"\x17GetTenantConfigResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12X\n" +
	"\x06values\x18\x02 \x01(\v2@.kms.api.cmk.registry.tenant_config.v1.TenantConfigurationValuesR\x06values\x12Q\n" +
	"\x06status\x18\x03 \x01(\x0e29.kms.api.cmk.registry.tenant_config.v1.TenantConfigStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xd8\x01\n" +
	"\x19UpdateTenantConfigRequest\x12$\n" +
	"\ttenant_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\btenantId\x12X\n" +
	"\x06values\x18\x02 \x01(\v2@.kms.api.cmk.registry.tenant_config.v1.TenantConfigurationValuesR\x06values\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x1c\n" +
	"\x1aUpdateTenantConfigResponse*\xa7\x01\n" +
	"\x12TenantConfigStatus\x12$\n" +
	" TENANT_CONFIG_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dTENANT_CONFIG_STATUS_UPDATING\x10\x01\x12'\n" +
	"#TENANT_CONFIG_STATUS_UPDATING_ERROR\x10\x02\x12\x1f\n" +
	"\x1bTENANT_CONFIG_STATUS_ACTIVE\x10\x03*[\n" +
	"\x12TenantConfigAction\x12$\n" +
	" TENANT_CONFIG_ACTION_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bTENANT_CONFIG_ACTION_UPDATE\x10\x012\xbc\x02\n" +
	"\aService\x12\x92\x01\n" +
	"\x0fGetTenantConfig\x12=.kms.api.cmk.registry.tenant_config.v1.GetTenantConfigRequest\x1a>.kms.api.cmk.registry.tenant_config.v1.GetTenantConfigResponse\"\x00\x12\x9b\x01\n" +
	"\x12UpdateTenantConfig\x12@.kms.api.cmk.registry.tenant_config.v1.UpdateTenantConfigRequest\x1aA.kms.api.cmk.registry.tenant_config.v1.UpdateTenantConfigResponse\"\x00BWZUgithub.com/openkcm/api-sdk/proto/kms/api/cmk/registry/tenant_config/v1;tenantconfigv1b\x06proto3"

var (
	file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDescOnce sync.Once
	file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDescData []byte
)

func file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDescGZIP() []byte {
	file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDescOnce.Do(func() {
		file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDesc), len(file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDesc)))
	})
	return file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDescData
}

var file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_goTypes = []any{
	(TenantConfigStatus)(0),            // 0: kms.api.cmk.registry.tenant_config.v1.TenantConfigStatus
	(TenantConfigAction)(0),            // 1: kms.api.cmk.registry.tenant_config.v1.TenantConfigAction
	(*TenantConfigurationValues)(nil),  // 2: kms.api.cmk.registry.tenant_config.v1.TenantConfigurationValues
	(*GetTenantConfigRequest)(nil),     // 3: kms.api.cmk.registry.tenant_config.v1.GetTenantConfigRequest
	(*GetTenantConfigResponse)(nil),    // 4: kms.api.cmk.registry.tenant_config.v1.GetTenantConfigResponse
	(*UpdateTenantConfigRequest)(nil),  // 5: kms.api.cmk.registry.tenant_config.v1.UpdateTenantConfigRequest
	(*UpdateTenantConfigResponse)(nil), // 6: kms.api.cmk.registry.tenant_config.v1.UpdateTenantConfigResponse
	(*fieldmaskpb.FieldMask)(nil),      // 7: google.protobuf.FieldMask
}
var file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_depIdxs = []int32{
	2, // 0: kms.api.cmk.registry.tenant_config.v1.GetTenantConfigResponse.values:type_name -> kms.api.cmk.registry.tenant_config.v1.TenantConfigurationValues
	0, // 1: kms.api.cmk.registry.tenant_config.v1.GetTenantConfigResponse.status:type_name -> kms.api.cmk.registry.tenant_config.v1.TenantConfigStatus
	2, // 2: kms.api.cmk.registry.tenant_config.v1.UpdateTenantConfigRequest.values:type_name -> kms.api.cmk.registry.tenant_config.v1.TenantConfigurationValues
	7, // 3: kms.api.cmk.registry.tenant_config.v1.UpdateTenantConfigRequest.update_mask:type_name -> google.protobuf.FieldMask
	3, // 4: kms.api.cmk.registry.tenant_config.v1.Service.GetTenantConfig:input_type -> kms.api.cmk.registry.tenant_config.v1.GetTenantConfigRequest
	5, // 5: kms.api.cmk.registry.tenant_config.v1.Service.UpdateTenantConfig:input_type -> kms.api.cmk.registry.tenant_config.v1.UpdateTenantConfigRequest
	4, // 6: kms.api.cmk.registry.tenant_config.v1.Service.GetTenantConfig:output_type -> kms.api.cmk.registry.tenant_config.v1.GetTenantConfigResponse
	6, // 7: kms.api.cmk.registry.tenant_config.v1.Service.UpdateTenantConfig:output_type -> kms.api.cmk.registry.tenant_config.v1.UpdateTenantConfigResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_init() }
func file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_init() {
	if File_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto != nil {
		return
	}
	file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDesc), len(file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_goTypes,
		DependencyIndexes: file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_depIdxs,
		EnumInfos:         file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_enumTypes,
		MessageInfos:      file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_msgTypes,
	}.Build()
	File_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto = out.File
	file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_goTypes = nil
	file_kms_api_cmk_registry_tenant_config_v1_tenant_config_proto_depIdxs = nil
}
