// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kms/api/cmk/sessionmanager/session/v1/session.proto

package sessionv1

import (
	v1 "github.com/openkcm/api-sdk/proto/kms/api/cmk/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,3,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_kms_api_cmk_sessionmanager_session_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_sessionmanager_session_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_sessionmanager_session_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetSessionRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	GivenName     string                 `protobuf:"bytes,4,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName    string                 `protobuf:"bytes,5,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Groups        []string               `protobuf:"bytes,7,rep,name=groups,proto3" json:"groups,omitempty"`
	AuthContext   map[string]string      `protobuf:"bytes,8,rep,name=auth_context,json=authContext,proto3" json:"auth_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_kms_api_cmk_sessionmanager_session_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_sessionmanager_session_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_sessionmanager_session_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *GetSessionResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *GetSessionResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GetSessionResponse) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *GetSessionResponse) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *GetSessionResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetSessionResponse) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GetSessionResponse) GetAuthContext() map[string]string {
	if x != nil {
		return x.AuthContext
	}
	return nil
}

type GetOIDCProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOIDCProviderRequest) Reset() {
	*x = GetOIDCProviderRequest{}
	mi := &file_kms_api_cmk_sessionmanager_session_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOIDCProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOIDCProviderRequest) ProtoMessage() {}

func (x *GetOIDCProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_sessionmanager_session_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOIDCProviderRequest.ProtoReflect.Descriptor instead.
func (*GetOIDCProviderRequest) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_sessionmanager_session_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *GetOIDCProviderRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetOIDCProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *v1.OIDCProvider       `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOIDCProviderResponse) Reset() {
	*x = GetOIDCProviderResponse{}
	mi := &file_kms_api_cmk_sessionmanager_session_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOIDCProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOIDCProviderResponse) ProtoMessage() {}

func (x *GetOIDCProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_sessionmanager_session_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOIDCProviderResponse.ProtoReflect.Descriptor instead.
func (*GetOIDCProviderResponse) Descriptor() ([]byte, []int) {
	return file_kms_api_cmk_sessionmanager_session_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *GetOIDCProviderResponse) GetProvider() *v1.OIDCProvider {
	if x != nil {
		return x.Provider
	}
	return nil
}

var File_kms_api_cmk_sessionmanager_session_v1_session_proto protoreflect.FileDescriptor

const file_kms_api_cmk_sessionmanager_session_v1_session_proto_rawDesc = "" +
	"\n" +
	"3kms/api/cmk/sessionmanager/session/v1/session.proto\x12%kms.api.cmk.sessionmanager.session.v1\x1a\x1fkms/api/cmk/types/v1/oidc.proto\"q\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12 \n" +
	"\vfingerprint\x18\x03 \x01(\tR\vfingerprint\"\xf9\x02\n" +
	"\x12GetSessionResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"given_name\x18\x04 \x01(\tR\tgivenName\x12\x1f\n" +
	"\vfamily_name\x18\x05 \x01(\tR\n" +
	"familyName\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x16\n" +
	"\x06groups\x18\a \x03(\tR\x06groups\x12m\n" +
	"\fauth_context\x18\b \x03(\v2J.kms.api.cmk.sessionmanager.session.v1.GetSessionResponse.AuthContextEntryR\vauthContext\x1a>\n" +
	"\x10AuthContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x16GetOIDCProviderRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"Y\n" +
	"\x17GetOIDCProviderResponse\x12>\n" +
	"\bprovider\x18\x01 \x01(\v2\".kms.api.cmk.types.v1.OIDCProviderR\bprovider2\xa4\x02\n" +
	"\aService\x12\x83\x01\n" +
	"\n" +
	"GetSession\x128.kms.api.cmk.sessionmanager.session.v1.GetSessionRequest\x1a9.kms.api.cmk.sessionmanager.session.v1.GetSessionResponse\"\x00\x12\x92\x01\n" +
	"\x0fGetOIDCProvider\x12=.kms.api.cmk.sessionmanager.session.v1.GetOIDCProviderRequest\x1a>.kms.api.cmk.sessionmanager.session.v1.GetOIDCProviderResponse\"\x00B\xc6\x02\n" +
	")com.kms.api.cmk.sessionmanager.session.v1B\fSessionProtoP\x01ZPgithub.com/openkcm/api-sdk/proto/kms/api/cmk/sessionmanager/session/v1;sessionv1\xa2\x02\x05KACSS\xaa\x02%Kms.Api.Cmk.Sessionmanager.Session.V1\xca\x02%Kms\\Api\\Cmk\\Sessionmanager\\Session\\V1\xe2\x021Kms\\Api\\Cmk\\Sessionmanager\\Session\\V1\\GPBMetadata\xea\x02*Kms::Api::Cmk::Sessionmanager::Session::V1b\x06proto3"

var (
	file_kms_api_cmk_sessionmanager_session_v1_session_proto_rawDescOnce sync.Once
	file_kms_api_cmk_sessionmanager_session_v1_session_proto_rawDescData []byte
)

func file_kms_api_cmk_sessionmanager_session_v1_session_proto_rawDescGZIP() []byte {
	file_kms_api_cmk_sessionmanager_session_v1_session_proto_rawDescOnce.Do(func() {
		file_kms_api_cmk_sessionmanager_session_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kms_api_cmk_sessionmanager_session_v1_session_proto_rawDesc), len(file_kms_api_cmk_sessionmanager_session_v1_session_proto_rawDesc)))
	})
	return file_kms_api_cmk_sessionmanager_session_v1_session_proto_rawDescData
}

var file_kms_api_cmk_sessionmanager_session_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kms_api_cmk_sessionmanager_session_v1_session_proto_goTypes = []any{
	(*GetSessionRequest)(nil),       // 0: kms.api.cmk.sessionmanager.session.v1.GetSessionRequest
	(*GetSessionResponse)(nil),      // 1: kms.api.cmk.sessionmanager.session.v1.GetSessionResponse
	(*GetOIDCProviderRequest)(nil),  // 2: kms.api.cmk.sessionmanager.session.v1.GetOIDCProviderRequest
	(*GetOIDCProviderResponse)(nil), // 3: kms.api.cmk.sessionmanager.session.v1.GetOIDCProviderResponse
	nil,                             // 4: kms.api.cmk.sessionmanager.session.v1.GetSessionResponse.AuthContextEntry
	(*v1.OIDCProvider)(nil),         // 5: kms.api.cmk.types.v1.OIDCProvider
}
var file_kms_api_cmk_sessionmanager_session_v1_session_proto_depIdxs = []int32{
	4, // 0: kms.api.cmk.sessionmanager.session.v1.GetSessionResponse.auth_context:type_name -> kms.api.cmk.sessionmanager.session.v1.GetSessionResponse.AuthContextEntry
	5, // 1: kms.api.cmk.sessionmanager.session.v1.GetOIDCProviderResponse.provider:type_name -> kms.api.cmk.types.v1.OIDCProvider
	0, // 2: kms.api.cmk.sessionmanager.session.v1.Service.GetSession:input_type -> kms.api.cmk.sessionmanager.session.v1.GetSessionRequest
	2, // 3: kms.api.cmk.sessionmanager.session.v1.Service.GetOIDCProvider:input_type -> kms.api.cmk.sessionmanager.session.v1.GetOIDCProviderRequest
	1, // 4: kms.api.cmk.sessionmanager.session.v1.Service.GetSession:output_type -> kms.api.cmk.sessionmanager.session.v1.GetSessionResponse
	3, // 5: kms.api.cmk.sessionmanager.session.v1.Service.GetOIDCProvider:output_type -> kms.api.cmk.sessionmanager.session.v1.GetOIDCProviderResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kms_api_cmk_sessionmanager_session_v1_session_proto_init() }
func file_kms_api_cmk_sessionmanager_session_v1_session_proto_init() {
	if File_kms_api_cmk_sessionmanager_session_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kms_api_cmk_sessionmanager_session_v1_session_proto_rawDesc), len(file_kms_api_cmk_sessionmanager_session_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kms_api_cmk_sessionmanager_session_v1_session_proto_goTypes,
		DependencyIndexes: file_kms_api_cmk_sessionmanager_session_v1_session_proto_depIdxs,
		MessageInfos:      file_kms_api_cmk_sessionmanager_session_v1_session_proto_msgTypes,
	}.Build()
	File_kms_api_cmk_sessionmanager_session_v1_session_proto = out.File
	file_kms_api_cmk_sessionmanager_session_v1_session_proto_goTypes = nil
	file_kms_api_cmk_sessionmanager_session_v1_session_proto_depIdxs = nil
}
