// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kms/api/cmk/sessionmanager/session/v1/session.proto

package sessionv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetSessionRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetSessionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSessionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSessionRequestMultiError, or nil if none found.
func (m *GetSessionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSessionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SessionId

	// no validation rules for TenantId

	// no validation rules for Fingerprint

	if len(errors) > 0 {
		return GetSessionRequestMultiError(errors)
	}

	return nil
}

// GetSessionRequestMultiError is an error wrapping multiple validation errors
// returned by GetSessionRequest.ValidateAll() if the designated constraints
// aren't met.
type GetSessionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSessionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSessionRequestMultiError) AllErrors() []error { return m }

// GetSessionRequestValidationError is the validation error returned by
// GetSessionRequest.Validate if the designated constraints aren't met.
type GetSessionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSessionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSessionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSessionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSessionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSessionRequestValidationError) ErrorName() string {
	return "GetSessionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSessionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSessionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSessionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSessionRequestValidationError{}

// Validate checks the field values on GetSessionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSessionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSessionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSessionResponseMultiError, or nil if none found.
func (m *GetSessionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSessionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Valid

	// no validation rules for Issuer

	// no validation rules for Subject

	// no validation rules for GivenName

	// no validation rules for FamilyName

	// no validation rules for Email

	// no validation rules for AuthContext

	if len(errors) > 0 {
		return GetSessionResponseMultiError(errors)
	}

	return nil
}

// GetSessionResponseMultiError is an error wrapping multiple validation errors
// returned by GetSessionResponse.ValidateAll() if the designated constraints
// aren't met.
type GetSessionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSessionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSessionResponseMultiError) AllErrors() []error { return m }

// GetSessionResponseValidationError is the validation error returned by
// GetSessionResponse.Validate if the designated constraints aren't met.
type GetSessionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSessionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSessionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSessionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSessionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSessionResponseValidationError) ErrorName() string {
	return "GetSessionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetSessionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSessionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSessionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSessionResponseValidationError{}
