// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kms/api/cmk/trust/oidc/v1/oidc.proto

package oidcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OIDC struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Issuer      *string                `protobuf:"bytes,1,opt,name=issuer"`
	xxx_hidden_ClientId    *string                `protobuf:"bytes,2,opt,name=client_id,json=clientId"`
	xxx_hidden_JwksUri     *string                `protobuf:"bytes,3,opt,name=jwks_uri,json=jwksUri"`
	xxx_hidden_Audiences   []string               `protobuf:"bytes,4,rep,name=audiences"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	extensionFields        protoimpl.ExtensionFields
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OIDC) Reset() {
	*x = OIDC{}
	mi := &file_kms_api_cmk_trust_oidc_v1_oidc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OIDC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDC) ProtoMessage() {}

func (x *OIDC) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_trust_oidc_v1_oidc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OIDC) GetIssuer() string {
	if x != nil {
		if x.xxx_hidden_Issuer != nil {
			return *x.xxx_hidden_Issuer
		}
		return ""
	}
	return ""
}

func (x *OIDC) GetClientId() string {
	if x != nil {
		if x.xxx_hidden_ClientId != nil {
			return *x.xxx_hidden_ClientId
		}
		return ""
	}
	return ""
}

func (x *OIDC) GetJwksUri() string {
	if x != nil {
		if x.xxx_hidden_JwksUri != nil {
			return *x.xxx_hidden_JwksUri
		}
		return ""
	}
	return ""
}

func (x *OIDC) GetAudiences() []string {
	if x != nil {
		return x.xxx_hidden_Audiences
	}
	return nil
}

func (x *OIDC) SetIssuer(v string) {
	x.xxx_hidden_Issuer = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *OIDC) SetClientId(v string) {
	x.xxx_hidden_ClientId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *OIDC) SetJwksUri(v string) {
	x.xxx_hidden_JwksUri = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *OIDC) SetAudiences(v []string) {
	x.xxx_hidden_Audiences = v
}

func (x *OIDC) HasIssuer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OIDC) HasClientId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OIDC) HasJwksUri() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *OIDC) ClearIssuer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Issuer = nil
}

func (x *OIDC) ClearClientId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ClientId = nil
}

func (x *OIDC) ClearJwksUri() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_JwksUri = nil
}

type OIDC_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Issuer    *string
	ClientId  *string
	JwksUri   *string
	Audiences []string
}

func (b0 OIDC_builder) Build() *OIDC {
	m0 := &OIDC{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Issuer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Issuer = b.Issuer
	}
	if b.ClientId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_ClientId = b.ClientId
	}
	if b.JwksUri != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_JwksUri = b.JwksUri
	}
	x.xxx_hidden_Audiences = b.Audiences
	return m0
}

var File_kms_api_cmk_trust_oidc_v1_oidc_proto protoreflect.FileDescriptor

const file_kms_api_cmk_trust_oidc_v1_oidc_proto_rawDesc = "" +
	"\n" +
	"$kms/api/cmk/trust/oidc/v1/oidc.proto\x12\x19kms.api.cmk.trust.oidc.v1\"\x91\x01\n" +
	"\x04OIDC\x12\x1e\n" +
	"\x06issuer\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06issuer\x12#\n" +
	"\tclient_id\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\bclientId\x12\x19\n" +
	"\bjwks_uri\x18\x03 \x01(\tR\ajwksUri\x12\x1c\n" +
	"\taudiences\x18\x04 \x03(\tR\taudiences*\x04\b2\x10d*\x05\bd\x10\xc8\x01BCZAgithub.com/openkcm/api-sdk/proto/kms/api/cmk/trust/oidc/v1;oidcv1b\beditionsp\xe9\az\x1bbuf/validate/validate.proto"

var file_kms_api_cmk_trust_oidc_v1_oidc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kms_api_cmk_trust_oidc_v1_oidc_proto_goTypes = []any{
	(*OIDC)(nil), // 0: kms.api.cmk.trust.oidc.v1.OIDC
}
var file_kms_api_cmk_trust_oidc_v1_oidc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kms_api_cmk_trust_oidc_v1_oidc_proto_init() }
func file_kms_api_cmk_trust_oidc_v1_oidc_proto_init() {
	if File_kms_api_cmk_trust_oidc_v1_oidc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kms_api_cmk_trust_oidc_v1_oidc_proto_rawDesc), len(file_kms_api_cmk_trust_oidc_v1_oidc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kms_api_cmk_trust_oidc_v1_oidc_proto_goTypes,
		DependencyIndexes: file_kms_api_cmk_trust_oidc_v1_oidc_proto_depIdxs,
		MessageInfos:      file_kms_api_cmk_trust_oidc_v1_oidc_proto_msgTypes,
	}.Build()
	File_kms_api_cmk_trust_oidc_v1_oidc_proto = out.File
	file_kms_api_cmk_trust_oidc_v1_oidc_proto_goTypes = nil
	file_kms_api_cmk_trust_oidc_v1_oidc_proto_depIdxs = nil
}
