// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kms/api/cmk/rpc/v1/error_details.proto

package rpcv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PreconditionFailure with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PreconditionFailure) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PreconditionFailure with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PreconditionFailureMultiError, or nil if none found.
func (m *PreconditionFailure) ValidateAll() error {
	return m.validate(true)
}

func (m *PreconditionFailure) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetViolations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PreconditionFailureValidationError{
						field:  fmt.Sprintf("Violations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PreconditionFailureValidationError{
						field:  fmt.Sprintf("Violations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PreconditionFailureValidationError{
					field:  fmt.Sprintf("Violations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return PreconditionFailureMultiError(errors)
	}

	return nil
}

// PreconditionFailureMultiError is an error wrapping multiple validation
// errors returned by PreconditionFailure.ValidateAll() if the designated
// constraints aren't met.
type PreconditionFailureMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PreconditionFailureMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PreconditionFailureMultiError) AllErrors() []error { return m }

// PreconditionFailureValidationError is the validation error returned by
// PreconditionFailure.Validate if the designated constraints aren't met.
type PreconditionFailureValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PreconditionFailureValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PreconditionFailureValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PreconditionFailureValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PreconditionFailureValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PreconditionFailureValidationError) ErrorName() string {
	return "PreconditionFailureValidationError"
}

// Error satisfies the builtin error interface
func (e PreconditionFailureValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPreconditionFailure.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PreconditionFailureValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PreconditionFailureValidationError{}

// Validate checks the field values on PreconditionFailure_Violation with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PreconditionFailure_Violation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PreconditionFailure_Violation with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// PreconditionFailure_ViolationMultiError, or nil if none found.
func (m *PreconditionFailure_Violation) ValidateAll() error {
	return m.validate(true)
}

func (m *PreconditionFailure_Violation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for Subject

	// no validation rules for Description

	if len(errors) > 0 {
		return PreconditionFailure_ViolationMultiError(errors)
	}

	return nil
}

// PreconditionFailure_ViolationMultiError is an error wrapping multiple
// validation errors returned by PreconditionFailure_Violation.ValidateAll()
// if the designated constraints aren't met.
type PreconditionFailure_ViolationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PreconditionFailure_ViolationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PreconditionFailure_ViolationMultiError) AllErrors() []error { return m }

// PreconditionFailure_ViolationValidationError is the validation error
// returned by PreconditionFailure_Violation.Validate if the designated
// constraints aren't met.
type PreconditionFailure_ViolationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PreconditionFailure_ViolationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PreconditionFailure_ViolationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PreconditionFailure_ViolationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PreconditionFailure_ViolationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PreconditionFailure_ViolationValidationError) ErrorName() string {
	return "PreconditionFailure_ViolationValidationError"
}

// Error satisfies the builtin error interface
func (e PreconditionFailure_ViolationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPreconditionFailure_Violation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PreconditionFailure_ViolationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PreconditionFailure_ViolationValidationError{}
