// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: kms/api/cmk/trust/v1/trust.proto

package trustv1

import (
	v1 "github.com/openkcm/api-sdk/proto/kms/api/cmk/trust/oidc/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trust struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId    *string                `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId"`
	xxx_hidden_Blocked     bool                   `protobuf:"varint,2,opt,name=blocked"`
	xxx_hidden_Details     isTrust_Details        `protobuf_oneof:"details"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Trust) Reset() {
	*x = Trust{}
	mi := &file_kms_api_cmk_trust_v1_trust_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trust) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trust) ProtoMessage() {}

func (x *Trust) ProtoReflect() protoreflect.Message {
	mi := &file_kms_api_cmk_trust_v1_trust_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Trust) GetTenantId() string {
	if x != nil {
		if x.xxx_hidden_TenantId != nil {
			return *x.xxx_hidden_TenantId
		}
		return ""
	}
	return ""
}

func (x *Trust) GetBlocked() bool {
	if x != nil {
		return x.xxx_hidden_Blocked
	}
	return false
}

func (x *Trust) GetOidc() *v1.OIDC {
	if x != nil {
		if x, ok := x.xxx_hidden_Details.(*trust_Oidc); ok {
			return x.Oidc
		}
	}
	return nil
}

func (x *Trust) SetTenantId(v string) {
	x.xxx_hidden_TenantId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *Trust) SetBlocked(v bool) {
	x.xxx_hidden_Blocked = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Trust) SetOidc(v *v1.OIDC) {
	if v == nil {
		x.xxx_hidden_Details = nil
		return
	}
	x.xxx_hidden_Details = &trust_Oidc{v}
}

func (x *Trust) HasTenantId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Trust) HasBlocked() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Trust) HasDetails() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Details != nil
}

func (x *Trust) HasOidc() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Details.(*trust_Oidc)
	return ok
}

func (x *Trust) ClearTenantId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TenantId = nil
}

func (x *Trust) ClearBlocked() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Blocked = false
}

func (x *Trust) ClearDetails() {
	x.xxx_hidden_Details = nil
}

func (x *Trust) ClearOidc() {
	if _, ok := x.xxx_hidden_Details.(*trust_Oidc); ok {
		x.xxx_hidden_Details = nil
	}
}

const Trust_Details_not_set_case case_Trust_Details = 0
const Trust_Oidc_case case_Trust_Details = 3

func (x *Trust) WhichDetails() case_Trust_Details {
	if x == nil {
		return Trust_Details_not_set_case
	}
	switch x.xxx_hidden_Details.(type) {
	case *trust_Oidc:
		return Trust_Oidc_case
	default:
		return Trust_Details_not_set_case
	}
}

type Trust_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId *string
	Blocked  *bool
	// Fields of oneof xxx_hidden_Details:
	Oidc *v1.OIDC
	// -- end of xxx_hidden_Details
}

func (b0 Trust_builder) Build() *Trust {
	m0 := &Trust{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TenantId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_TenantId = b.TenantId
	}
	if b.Blocked != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Blocked = *b.Blocked
	}
	if b.Oidc != nil {
		x.xxx_hidden_Details = &trust_Oidc{b.Oidc}
	}
	return m0
}

type case_Trust_Details protoreflect.FieldNumber

func (x case_Trust_Details) String() string {
	md := file_kms_api_cmk_trust_v1_trust_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isTrust_Details interface {
	isTrust_Details()
}

type trust_Oidc struct {
	Oidc *v1.OIDC `protobuf:"bytes,3,opt,name=oidc,oneof"` // kms.api.cmk.trust.saml.v1 Trust saml = 4; // We may add SAML later
}

func (*trust_Oidc) isTrust_Details() {}

var File_kms_api_cmk_trust_v1_trust_proto protoreflect.FileDescriptor

const file_kms_api_cmk_trust_v1_trust_proto_rawDesc = "" +
	"\n" +
	" kms/api/cmk/trust/v1/trust.proto\x12\x14kms.api.cmk.trust.v1\x1a$kms/api/cmk/trust/oidc/v1/oidc.proto\"\x8f\x01\n" +
	"\x05Trust\x12#\n" +
	"\ttenant_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\btenantId\x12\x18\n" +
	"\ablocked\x18\x02 \x01(\bR\ablocked\x125\n" +
	"\x04oidc\x18\x03 \x01(\v2\x1f.kms.api.cmk.trust.oidc.v1.OIDCH\x00R\x04oidcB\x10\n" +
	"\adetails\x12\x05\xbaH\x02\b\x01B?Z=github.com/openkcm/api-sdk/proto/kms/api/cmk/trust/v1;trustv1b\beditionsp\xe9\az\x1bbuf/validate/validate.proto"

var file_kms_api_cmk_trust_v1_trust_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kms_api_cmk_trust_v1_trust_proto_goTypes = []any{
	(*Trust)(nil),   // 0: kms.api.cmk.trust.v1.Trust
	(*v1.OIDC)(nil), // 1: kms.api.cmk.trust.oidc.v1.OIDC
}
var file_kms_api_cmk_trust_v1_trust_proto_depIdxs = []int32{
	1, // 0: kms.api.cmk.trust.v1.Trust.oidc:type_name -> kms.api.cmk.trust.oidc.v1.OIDC
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kms_api_cmk_trust_v1_trust_proto_init() }
func file_kms_api_cmk_trust_v1_trust_proto_init() {
	if File_kms_api_cmk_trust_v1_trust_proto != nil {
		return
	}
	file_kms_api_cmk_trust_v1_trust_proto_msgTypes[0].OneofWrappers = []any{
		(*trust_Oidc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kms_api_cmk_trust_v1_trust_proto_rawDesc), len(file_kms_api_cmk_trust_v1_trust_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kms_api_cmk_trust_v1_trust_proto_goTypes,
		DependencyIndexes: file_kms_api_cmk_trust_v1_trust_proto_depIdxs,
		MessageInfos:      file_kms_api_cmk_trust_v1_trust_proto_msgTypes,
	}.Build()
	File_kms_api_cmk_trust_v1_trust_proto = out.File
	file_kms_api_cmk_trust_v1_trust_proto_goTypes = nil
	file_kms_api_cmk_trust_v1_trust_proto_depIdxs = nil
}
