// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kms/api/cmk/eventprocessor/v1/task.proto

package taskv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Data with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Data) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Data with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DataMultiError, or nil if none found.
func (m *Data) ValidateAll() error {
	return m.validate(true)
}

func (m *Data) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TaskType

	switch v := m.Data.(type) {
	case *Data_KeyAction:
		if v == nil {
			err := DataValidationError{
				field:  "Data",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetKeyAction()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DataValidationError{
						field:  "KeyAction",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DataValidationError{
						field:  "KeyAction",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetKeyAction()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DataValidationError{
					field:  "KeyAction",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *Data_SystemAction:
		if v == nil {
			err := DataValidationError{
				field:  "Data",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetSystemAction()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DataValidationError{
						field:  "SystemAction",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DataValidationError{
						field:  "SystemAction",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetSystemAction()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DataValidationError{
					field:  "SystemAction",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return DataMultiError(errors)
	}

	return nil
}

// DataMultiError is an error wrapping multiple validation errors returned by
// Data.ValidateAll() if the designated constraints aren't met.
type DataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DataMultiError) AllErrors() []error { return m }

// DataValidationError is the validation error returned by Data.Validate if the
// designated constraints aren't met.
type DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DataValidationError) ErrorName() string { return "DataValidationError" }

// Error satisfies the builtin error interface
func (e DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DataValidationError{}

// Validate checks the field values on KeyAction with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *KeyAction) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on KeyAction with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in KeyActionMultiError, or nil
// if none found.
func (m *KeyAction) ValidateAll() error {
	return m.validate(true)
}

func (m *KeyAction) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for KeyId

	// no validation rules for TenantId

	// no validation rules for CmkRegion

	if len(errors) > 0 {
		return KeyActionMultiError(errors)
	}

	return nil
}

// KeyActionMultiError is an error wrapping multiple validation errors returned
// by KeyAction.ValidateAll() if the designated constraints aren't met.
type KeyActionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m KeyActionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m KeyActionMultiError) AllErrors() []error { return m }

// KeyActionValidationError is the validation error returned by
// KeyAction.Validate if the designated constraints aren't met.
type KeyActionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e KeyActionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e KeyActionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e KeyActionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e KeyActionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e KeyActionValidationError) ErrorName() string { return "KeyActionValidationError" }

// Error satisfies the builtin error interface
func (e KeyActionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sKeyAction.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = KeyActionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = KeyActionValidationError{}

// Validate checks the field values on SystemAction with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SystemAction) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SystemAction with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SystemActionMultiError, or
// nil if none found.
func (m *SystemAction) ValidateAll() error {
	return m.validate(true)
}

func (m *SystemAction) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SystemId

	// no validation rules for SystemRegion

	// no validation rules for SystemType

	// no validation rules for KeyIdFrom

	// no validation rules for KeyIdTo

	// no validation rules for KeyProvider

	// no validation rules for KeyAccessMetaData

	// no validation rules for TenantId

	// no validation rules for TenantOwnerId

	// no validation rules for TenantOwnerType

	// no validation rules for CmkRegion

	if len(errors) > 0 {
		return SystemActionMultiError(errors)
	}

	return nil
}

// SystemActionMultiError is an error wrapping multiple validation errors
// returned by SystemAction.ValidateAll() if the designated constraints aren't met.
type SystemActionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SystemActionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SystemActionMultiError) AllErrors() []error { return m }

// SystemActionValidationError is the validation error returned by
// SystemAction.Validate if the designated constraints aren't met.
type SystemActionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SystemActionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SystemActionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SystemActionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SystemActionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SystemActionValidationError) ErrorName() string { return "SystemActionValidationError" }

// Error satisfies the builtin error interface
func (e SystemActionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSystemAction.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SystemActionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SystemActionValidationError{}
