name: Release New Version

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: github.actor != 'dependabot[bot]'
    uses: openkcm/build/.github/workflows/release.lib.yaml@main
    secrets: inherit
